### ISSUE TITLE
Half height titles on 4.4.2 tablet

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#103]
In both the landscape and portrait modes, the titles are only
displaying the top half of the text.

@dmfrey, if you can point me to the place to change it, I'll experiment
and test with 4.4.2 and 6.0.1.

![halftitles](https://cloud.githubusercontent.com/assets/1831699/13906558/1668d75e-eea7-11e5-8fb3-2303878ef725.png)

**Comment by dmfrey** [comment]
What really needs to happen is we need to create a layout for landscape
views on tablets. It is one of the recommendations in the play dev console
to make it more friendly for tablets.

For example, look at the Google play store on the tablet, then rotate it
and note the difference. The extra margin on the sides, etc.
