### ISSUE TITLE
Implement Google Cast Support

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#106]
Work Branch:
https://github.com/MythTV-Clients/MythtvPlayerForAndroid/tree/feature/issue_106_implement_google_cast

**Comment by netwolfuk** [comment]
I presume you are referring to being able to control a ChromeCast from MPFA?

What sort of receiver did you envisage needing to build? Looking this [this video](https://www.youtube.com/watch?v=clhnfUMuhN8), there are three types. The StyledReceiver seems like the best fit to me, but the CustomReceiver gets special mention with regards to HLS.

I don't know anything about HLS other than I see a button for it inside the Player, so am not sure if it's really a requirement.

From watching that video, I have been able to glean that for the Styled and Custom receivers, the ChromeCast looks up the ID presented by the controller app by using in a Google service. This service redirects the ChromeCast to an HTML5 page containing the receiver implemenation. 
I initially thought this could be hosted in MythWeb locally on the MythTV server, but since it's google returning the URL, it would need to be on the internet somewhere. It could probably be served from github.io in the short-term. I'm not sure what GitHub's policy is on that sort of thing.

I'd be happy to help out if I can, and can test a ChromeCast (v1) and an Oppo BluRay player which supports the Cast version of the DIAL protocol.

Have you had a look at the NetFlix ChromeCast support? That seems to be the slickest Cast app I've seen. Also the RedBullTV one is good.

**Comment by dmfrey** [comment]
@netwolfuk Yes, the goal is to be able to present MythTV backend recordings and videos on Chromecast. I have committed what I have so far. You can select a local Chromecast device and disconnect from it at this point. Still no playback as of yet.

This should work with HLS transcoded recordings, mp4 and MKV files, according to the Supported Media Playback options.

I already have a Styled Media Receiver setup. It is not published at this time. You can send me the serial numbers for your devices and I can add you to the list so that you can test.

I believe a long term solution would be to have a custom receiver hosted on mythtv.org, if the devs are up for that. The styled one works for now.

**Comment by netwolfuk** [comment]
Cool! You're further ahead than I thought already. I'll dig out the serial numbers when I get a chance to sit down at the computer. 

I see your latest commit has broken the build on my build server. What do I need to do to install Google play services cast support?

**Comment by dmfrey** [comment]
You should just need to update the Gradle dependencies. Can you post a
stack trace?

**Comment by netwolfuk** [comment]
Sorry. Gradle noob here. This is the message in TeamCity.

[16:41:25][Step 3/3] ##teamcity[buildProblem identity='-518009078' description='org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.android.gms:play-services-cast:8.4.0.|nSearched in the following locations:|n    https://jcenter.bintray.com/com/google/android/gms/play-services-cast/8.4.0/play-services-cast-8.4.0.pom|n    https://jcenter.bintray.com/com/google/android/gms/play-services-cast/8.4.0/play-services-cast-8.4.0.jar|n    file:/opt/development/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-cast/8.4.0/play-services-cast-8.4.0.pom|n    file:/opt/development/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-cast/8.4.0/play-services-cast-8.4.0.jar|nRequired by:|n    a3a53d8962312a71:presentation:unspecified' type='gradleBuildProblem']

**Comment by netwolfuk** [comment]
Sorry. I'm a numpty. Google Repository was not installed on the build agent. Build is succeeding now.

**Comment by netwolfuk** [comment]
I can't figure out how to get the Chromecast developer page to see my BluRay player, so I only have the genuine Chromecast one for now: 3819101ZJJL5

**Comment by netwolfuk** [comment]
FYI, I have build your branch and installed it on my Nexus 4. I can't see a way to navigate to the AppCastPlayerActivity though. It does not appear in the menu on the left, or up by the seach icon.
I'll assume my Chromecast must be registered against your AppID for it to be available.

**Comment by dmfrey** [comment]
I need to add you serial number to my Google cast dev console. I will take
care of that in a few. Once I do, I will let you know. Then you have to
restart your Chromecast. It may take a few hours before it will see that it
can be used as a developer device. This is Google's docs that describe this.

The AppCastPlayerActivity is going to get called from the recording or
video details screens, only when you are connected to a cast device,
otherwise, the other play options will be called. I haven't quite figured
out how I want to do that part yet. It still needs to be refractored to
make it generic for videos or recordings.

**Comment by dmfrey** [comment]
@netwolfuk Your Chromecast has been added to the dev console. Reboot it. I will check back in a bit to see that it accepted the registration.  From my end it will say 'Ready for Testing' on the console.

**Comment by dmfrey** [comment]
@netwolfuk shoot me an email address and I can add you to the slack channel

**Comment by netwolfuk** [comment]
Yey. The icon has appeared. My Chromecast must've registered. Thanks!

**Comment by netwolfuk** [comment]
The email I use for slack is netwolfuk+slack at Gmail. I use the +slack to filter stuff in Gmail.

**Comment by dmfrey** [comment]
Yup, ready for testing. :-)

**Comment by dmfrey** [comment]
@billmeek @netwolfuk 

In order for this to work successfully, we will need to configure the backend to produce CORS Headers. Also, it is helpful for the backend to produce Content-Type, Accept-Encoding and Range Headers. How do we best go about getting Port 6544 to produce these. Content-Type is already there, but the others are not.  We can add these in a .htaccess file, but this would need to be a more permanent solution when installing mythtv backend.

Thoughts??

**Comment by billmeek** [comment]
@dmfrey I'll look into Access-Control-Allow-Origin: header,
now that I did some reading about it. What value would it return? Assuming
that * is too open and that in many cases, no domain name will be available,
only an IP?

**Comment by billmeek** [comment]
And then I caught up on my IRC reading...

**Comment by dmfrey** [comment]
we will still need to add those headers. Just not sure what to set for the
Range header. Content-type is already there.

**Comment by dmfrey** [comment]
SUCCESS!!! This works from the app, but only with an MP4 file, no extra headers required. Now the for the other streaming formats, we will need the other headers to get them to work.

**Comment by dmfrey** [comment]
closes #106

**Comment by trainerbill** [comment]
@dmfrey can you explain how to get this functionality?  I am not seeing a chrome cast button on the mythplayer app.

**Comment by dmfrey** [comment]
Here are a couple of things to check.

1. On the correct wifi network?
2. Are you running the latest beta?

When you are connected to the network, the Google Cast button should *just
appear* in the Action Bar. You then have to HLS transcode some recordings
and/or videos. Unfortunately, Google Cast doesn't MPEG2-TS, so you either
need an MP4 or HLS transcoding of the recording. Most video formats should
just work, however, you can always transcode them to HLS.

Let me know how it goes.

Dan

**Comment by trainerbill** [comment]
@dmfrey Thanks for the quick reply!

I am on 2.1.1, assuming i have to download the apk of the latest and install?  Chromecast not supporting MPEG2 is a real bummer.  

1.  How do the videos look using HLS?
2.  Can/does the app automatically start the HLS transcode when you start playing?  Or do you have to go to the mythbackend to start the HLS transcode?

**Comment by dmfrey** [comment]
Go to the G+ page and follow the instructions to join the beta.

The videos look fine so long as they are in a format Chromecast supports.
There is a page on the cast developer page that lists this. There are some
that just won't work as is.

Mpeg2 just doesn't have hardware coding support.

**Comment by trainerbill** [comment]
@dmfrey I have the beta and see the cast button now.  I create an HLS stream and cast and it looks like it is going to load and then just displays the MythPlayer blue screen on the TV.  I see the HLS stream on the Mythbackend and I can play the recording on my phone in the Mythplayer app, but casting doesn't work.  Let me know if you want me to submit a new issue and any other info you need.

**Comment by dmfrey** [comment]
@trainerbill Did you get by this?

Here is one thing to try. Google Cast can be debugged through Chrome.  Follow these instructions. https://developers.google.com/cast/docs/debugging

Let me know if you are still unable to access it and any relevant error reported in chrome.

**Comment by trainerbill** [comment]
No, I have not been able to get this working.

**Comment by dmfrey** [comment]
@trainerbill if i had to guess, It sounds like the cast receiver app (which runs on the chromecast itself), is can't communicate with your backend. I am running a HLS stream from my hotel room in indianapolis from my backend at my house in Pennsylvania.

**Comment by dmfrey** [comment]
@trainerbill can you play your HLS streams by going to http://you_backend_ip:6544, then navigate to API -> Examples -> HTTP Live Streaming? If not, there is an issue with producing viable streams on your backend.

**Comment by trainerbill** [comment]
thx @dmfrey.  It may have been my networking setup.  However, I ended up going with bubbleupnp.  It also allows me to connect and transcode from my HDHomeruns for live tv.

**Comment by dmfrey** [comment]
closes #106
