### ISSUE TITLE
Move all projects to OpenJDK 8

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#110]
In the latest canary builds, OpenJDK 8 is supported. It needs to be enabled in build.gradle.  

Consider bigger picture, remove rxJava, use straight Java 8 Lambda Expressions.

https://developer.android.com/preview/j8-jack.html

Further research is required.

**Comment by billmeek** [comment]
@dmfrey, FYI with Ubuntu 16.04 the following warning pops up
in Android Studio when it's started:
```
System Health
OpenJDK shows intermittent performance and UI issues. We recommend using the Oracle JRE/JDK.
```
I haven't seen any negative affects and the warning can be turned off. Never
saw the warning in Ubuntu 15.10 (and thought I was using Oracle JDK and still
have it installed.)

**Comment by dmfrey** [comment]
This is kind of just a placeholder for now. work is being done with the
android tools, etc to be able to implement this. It is supposed to allow
them to adopt the Java 8 Lambda Expressions and such much quicker. There
are some impressive improvements slated for Java 9 as well. The app as it
is today, doesn't really support this. I have, however, started a
standalone java project that aims to remove all the RxJava stuff in the
:data subproject with plain Java 8 Lamda Expressions. It will make the code
much lighter and much more easy to test. I don't really have a place to put
this at this point. I will find a repo and share it out if you want to take
a look at it.

**Comment by dmfrey** [comment]
I believe this has become more about moving to Java8 features. OpenJDK should just work, or Oracle JDK as well.
