### ISSUE TITLE
Allow the display and marking of episodes as watched (or unwatched)

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#112]
0.28 provides a new endpoint: Dvr/UpdateRecordedWatchedStatus. The
parameters are RecordedId (or ChanId and StartTime) plus a Watched
bool. This does not exist in 0.27 currently, but appears to be possible
with the exception of the RecordedId parameter. It's sent as a POST,
as expected.

In order to get the existing status of an episode, the ProgramFlags
key in Dvr/GetRecordedList is available, but is bit mapped:
```
{'ProgramList': 
  Programs':[{
    'ProgramFlags': '5633',
    'Title': 'Some Show Name,
```

The decimal ProgramFlags value above has the watched flag
in bit 9. The following from the 0.27/0.28 MythTV code:
```
#FL_WATCHED = 0x00000200 // As defined in: libs/libmyth/programtypes.h
https://code.mythtv.org/cgit/mythtv/tree/mythtv/libs/libmyth/programtypes.h#n133
```

**Comment by dmfrey** [comment]
@billmeek A couple of questions:
1. How do you envision displaying the watched status?
2. Should updating the watched status be handled by a button, or should this be handled on playback? If its playback, should it be when it starts? When playback ends?

**Comment by billmeek** [comment]
@dmfrey, I'd suggest text or an icon right of the title and above the channel.
But somewhere on a per episode basis.

I'd also suggest toggling the status with a button, as opposed to trying to make
it automatic.

**Comment by dmfrey** [comment]
@billmeek Is ProgramFlags comma separated? I assume it contains multiple flags, correct?  Are there any other we should consider displaying?

For display, I think we could hover these over the header image on the episode screen, along either the right or left side (or possibly both should there be many that need to be displayed)

**Comment by billmeek** [comment]
No, it's returned as a decimal value and watched is in bit 9
(as in 0-9 counting from the right.) Here's the hex from the
MythTV code: FL_WATCHED = 0x00000200. There's more
detail in the initial post of this issue if you like.

**Comment by dmfrey** [comment]
I am missing something here. I don't believe this will translate to a Java Decimal, resulting in the hex code.

**Comment by billmeek** [comment]
Does this make sense?
``` java
int ProgramFlags = 5633;
boolean Watched = (ProgramFlags | 0x2000) == 1;
```

**Comment by billmeek** [comment]
Maybe == 1 should just be > 0

**Comment by dmfrey** [comment]
ah, ok, I will play with that. I misunderstood.

**Comment by dmfrey** [comment]
@billmeek Give this a shot. Something is not right with the calculation. I'm still missing something. It always results to true.

**Comment by billmeek** [comment]
@dmfrey, true because I meant to say (ProgramFlags & 0x2000) > 0,
not |. Works good. Looks good too.

**Comment by billmeek** [comment]
Note that if the preview image for an episode is mostly
white in the area of the eye, it can't be seen.

**Comment by dmfrey** [comment]
Let me see if I can put a border on it, maybe make the background black or one of our colors.

**Comment by dmfrey** [comment]
@billmeek for your comment:

    true because I meant to say (ProgramFlags & 0x2000) > 0,
    not |. Works good. Looks good too.

Did you fix the code? If so, I don't see a commit for it.

Is the eye graphic switching on/off correctly in your version?

**Comment by billmeek** [comment]
Hi, I did commit on branch feature/issue_112_mark_watched
```
commit e8d605c76a09706415d7a2f853ca2f1624da39aa
Date:   Sat Apr 2 23:08:21 2016 -0500
```

The eye tracked the value of watched on the backend. I
didn't test to see if it changes dynamically if a mythfrontend
uses changes it. Pressing the eye to call UpdateRecordedWatchedStatus
isn't added yet,as far as I can tell, so I didn't try that.

**Comment by dmfrey** [comment]
Right, that isn't implemented yet. I was more interested in if the data turns it on/off. Will work on the web service next.

**Comment by billmeek** [comment]
Just pushing a 0.28 patch to let UpdateRecordedWatchedStatus
return false if the RecordId or ChanId/StartTime don't find a
matching recording.

I've got a patch tested to add the endpoint to 0.27 in MythTV too.
Having trouble with it's cousin UpdataVideoWatchedStatus
though.

**Comment by billmeek** [comment]
The new eye display works well on dark and even white
images.

**Comment by dmfrey** [comment]
cool, if the display is working just with the data alone, now we can turn
it into a toggle and call the web service to initiate this from within the
app

**Comment by billmeek** [comment]
@dmfrey, FYI, the Dvr/UpdateRecordedWatchedStatus and Video/UpdateVideoWatchedStatus
now exist in 0.27 (assuming folks do daily builds.) In both 0.27 and 0.28, the return is true if the
status was changed and false if the recording/video doesn't exist. A 501 is returned for Recorded
input that is invalid (ChanId, StartTime and in 0.28 RecordedId.) A 404 Error will be returned if
the endpoint doesn't exist.

I don't know that the video version is of use here (I don't mark mine as watched) but I added it
for consistency. I could be useful for those who move a TV series to Video and watch it there,
but that's another enhancement issue and I don't plan on raising it.

**Comment by dmfrey** [comment]
@billmeek, I have an initial implementation. I haven't got to test it yet,
however. I am gonna have to really inspect the values before I refactor
this to the current clean model.

What exactly does setting the watched flag do to the recording on the
backend? I don't use it.

**Comment by billmeek** [comment]
If set, watched recordings are expired before unwatched ones. There is
an option "Watched before unwatched" that controls this and it is set to
false by default. They also don't appear in the MythTV Watch List.

Here's a preview using my test program:
```
Valid cases:
bill@ofc0:~/source/mythtv$ api.py --wrmi --host=ofc0 --endpoint=Dvr/UpdateRecordedWatchedStatus --postdata ChanId=1501 StartTime=2016-04-04T23:30:00 Watched=true
{'bool': 'true'}
bill@ofc0:~/source/mythtv$ api.py --wrmi --host=ofc0 --endpoint=Dvr/UpdateRecordedWatchedStatus --postdata ChanId=1501 StartTime=2016-04-04T23:30:00 Watched=false
{'bool': 'true'}

StartTime changed (seconds don't match any existing recording)
bill@ofc0:~/source/mythtv$ api.py --wrmi --host=ofc0 --endpoint=Dvr/UpdateRecordedWatchedStatus --postdata ChanId=1501 StartTime=2016-04-04T23:30:09 Watched=false
{'bool': 'false'}

StartTime has an invalid timestamp ( seconds > 59) The error message is mine, but the 500 is correct,
I thought it was a 501, but it's 500.
bill@ofc0:~/source/mythtv$ api.py --wrmi --host=ofc0 --endpoint=Dvr/UpdateRecordedWatchedStatus --postdata ChanId=1501 StartTime=2016-04-04T23:30:99 Watched=false
{'Abort': 'Unexpected status returned: 500: URL was: http://ofc0:6544/Dvr/UpdateRecordedWatchedStatus'}
```

**Comment by billmeek** [comment]
Nice. When an app user toggles the Watched flag while in the
MythTV Watch Recordings screen for the affected recording, the
eye changes state. I won't test a lot while this is in progress,
but it's looking good.

**Comment by dmfrey** [comment]
@billmeek, what would the process be to update this flag locally. Are the
program flags a combination of those values, is that correct?

**Comment by billmeek** [comment]
@dmfrey, I was thinking that somewhere after this
successfully completed:
``` java
okHttpClient.newCall( request ).execute().body().string();
```
the app's copy of the programFlags would be changed. If the app turned Watched off,
then programFlags &= ~0x200 and if Watched was turned on, programFlags |= 0x200.
Maybe just toggling the previous value with an exclusive or would work, like
programFlags ^= 0x200.

If you can tell me where to put the logic, I'll test it and try to
use the exclusive or = method. I couldn't see how to access
programModel.getProgramFlags() where okHttpClient was
used above.

There is the possibility of a race condition, if a MythTV user
changes the status and the app user does too. Would have
to get the details for that specific recording to verify (get
the ProgramFlags again.)

**Comment by dmfrey** [comment]
i'm working on moving all this to the data layer. This might not be issue,
as I am planning on invalidating the local cache upon a true returned, and
refreshing the recordings, so that we will always have the freshest data.

**Comment by billmeek** [comment]
@dmfrey, if it's of interest, a new Get and Set SavedBookmark was just
contributed by a user and should make it into 0.28.1. Not sure if that is
important to your switch to the data layer.

**Comment by dmfrey** [comment]
@billmeek, what flag is there for videos in the data that indicates watched
or not?

**Comment by billmeek** [comment]
This one is easier, I think. From Video/GetVideo?Id=123:
```
...
'Collectionref': '-1',
'Watched': 'false',
'Studio': '',
...
