### ISSUE TITLE
Determine what requires API level 17

### ISSUE THREAD

**Issue by brianjmurrell** [MythTV-Clients/MythtvPlayerForAndroid#115]
Per the G+ conversation, it would be interesting to determine what is causing the requirement for API level 17 and if whatever that is can be worked around easily enough so as to be able to support Android versions < 4.2.

**Comment by dmfrey** [comment]
I don't recall the exact reason, however, it is probably related to items
in the Android Support Compatibility libraries that weren't up to date with
their counterparts in the API 21+.  However, an investigation will be
performed to see if we can backport it to API 16.

**Comment by dmfrey** [comment]
Initial review. The Android Leanback Libraries, required for Android TV, are preventing me from going back to Android SDK 14 (Ice Cream Sandwich). I will keep looking to see if there is any other way to configure the Android Manifest to allow the app to go back to 14.

**Comment by dmfrey** [comment]
@brianjmurrell I was able to get this working.

https://stackoverflow.com/questions/36587022/added-android-tv-to-existing-app-now-can-only-support-back-to-android-sdk-17

@billmeek I had to separate out the Android TV code from the Android App code.  There is now an :app and :tv subproject. The MVP code remains in the :presentation subproject. I will commit this shortly. Do you have a device still that you can test this out on?

**Comment by billmeek** [comment]
No 17, I've got: ICS/4.0.4/15, JB/4.4.2/19 and MM/6.0.1/23

**Comment by billmeek** [comment]
Ah, change the minSdkVersion to 14 in the app build.gradle for dev{}

```
$ adb shell am start -n "org.mythtv.android/org.mythtv.android.app.view.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Unexpected error while executing: am start -n "org.mythtv.android/org.mythtv.android.app.view.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while Launching activity
```

**Comment by dmfrey** [comment]
@billmeek, we just need something that is 14, 15, or 16. We know that 17+
is good.

**Comment by billmeek** [comment]
@dmfrey, sorry, had to go out for a bit. Just downloading the app
a 2nd time worked. Up and running on 15. 

On VLC playback of a 1080i recording, I get a frozen picture and
normal audio. With MPEG-2, it's A-OK. Both shows have the same
AC-3 and 5.1 audio.

**Comment by dmfrey** [comment]
@billmeek I am not sure that we can do anything about VLC playback. We are at least providing the capability for users with older devices. I tried it on an emulator and an old 4.4.2 phone and seems to be working ok.

Did HLS playback OK on that device?

If no other issues, I will do a PR and merge it into develop.

**Comment by billmeek** [comment]
@dmfrey, HLS  playback works, including skipping around. Only
tried on HD. I put the tablet away last night and when I turned
it on, there was an Unfortunately... message from this app. Also,
last night, I watched a Video and it played fine. But when it got
to the end, the tablet froze. I was eventually able to power down.
Not connected to Android Studio, so no LogCat on either.

I'd suggest holding off on the PR for now. I'll test more tonight.

**Comment by dmfrey** [comment]
@billmeek are we good to merge this in?

**Comment by billmeek** [comment]
Yes, go for it. I haven't seen the Unfortunately message for
over a week. And I've been going to the Recordings screen
every day.

**Comment by dmfrey** [comment]
cool, i will do a PR for this.

**Comment by brianjmurrell** [comment]
This is super cool!  I can't wait to be able to try it out on my middle-aged (but by no means over the hill :-)) tablet.
