### ISSUE TITLE
Internal Player: Pressing Volume Up/Down During Playback Displays Progress Bar

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#12]
The progress bar doesn't time out. Doesn't happen with VLC

**Comment by dmfrey** [comment]
Odd. I was not expecting this. I will look into this.

**Comment by billmeek** [comment]
I meant to add that the  progress bar never goes away
once it shows up ('til the recording ends of course.)
