### ISSUE TITLE
Add Details Header FAB to initiate playback

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#121]
This will remove the HLS Queue/Play button from the bottom of the Details screens.

**Comment by billmeek** [comment]
@dmfrey, along with #120, would you consider removing the
Internal/External player choices in Settings and allow the new
"starting/removing HLS transcode jobs" choices to also include
to "play external"? Just a thought. Hmmm, could also eliminate
the need for settings on the detail page (although users may 
want to change the transcoding parameters.)

**Comment by dmfrey** [comment]
So remove the Settings and pop a dialog that asks to play internal or
external when play is clicked?

Will probably leave the settings so that they can change the HLS settings.

**Comment by billmeek** [comment]
Yes, I was thinking that folks would choose External or Queue HLS
as each recording/video was played. I agree with keeping
the HLS settings (that's what I was trying to refer to with "transcoding
parameters".)

If I understand your intent, then I'm suggesting the user would see *like*:
```
Play (with external player)
Queue HLS
Delete Live Stream
```

**Comment by dmfrey** [comment]
Not quite. There will be a button, like update watched status to handle
add/remove hls stream. Play will just play whatever is available, but give
choice to play internal or external player.

**Comment by billmeek** [comment]
Got it/like it. I'm a bit concerned if there isn't a
'do you really want to do this' option when the
remove hsl stream is done.

But, your design intent is to make it a toggle (as you
wrote in 120.)

**Comment by netwolfuk** [comment]
By external player, do you mean VLC on Android device, or ChromeCast?

**Comment by billmeek** [comment]
@netwolfuk, yes, VLC or other players.

**Comment by dmfrey** [comment]
@billmeek what do you think of the FAB for playback? any issues switching between HLS and external player?  I still need to remove the separate preferences

**Comment by billmeek** [comment]
FAB is great. I should have answered this issue 1st tonight.

If HLS is off, then FAB = use external player
If HLS is on and the stream is available, then FAB = internal player and
then turning HLS off = delete live stream.

I still think there needs to be a 'we really mean it' of some sort
before deleting the stream.

**Comment by dmfrey** [comment]
@billmeek yes, that is mostly correct. If you specified the Internal player in the settings and hls is available it will use the internal player. If it is set to external, and hls is available, then it will go to external player. that is the one caveat.

How does the internal player work for you? I notice some interlacing going on. VLC is much smoother.

**Comment by billmeek** [comment]
I haven't spotted a difference. Maybe I need to record
a sporting event or something with quicker movement.
