### ISSUE TITLE
Some text overlaps pictures or other text in 4.0.4

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#122]
This happens in Watch Recordings on the Episode screen and the
Detail screen below it. Same for Video Details and Home screen
RECENT tab.

Branch feature/issue_115_lower_api_restriction was fine.

**Comment by billmeek** [comment]
The above is on feature/issue_120_hls_button, mythtv-player-2.0.1-36-gba7418f

Tested on the wrong branch. Closed.

**Comment by billmeek** [comment]
Reopening to track release/mythtv-player-2.0.3 regression.

**Comment by billmeek** [comment]
![overlap](https://cloud.githubusercontent.com/assets/1831699/14928736/5d52a8f6-0e1f-11e6-8115-20d824aee72d.jpg)

**Comment by dmfrey** [comment]
This looks like a margin isn't being set correctly anymore. Maybe a
dimens.xml file got overwritten. I will take a look tonight.

**Comment by dmfrey** [comment]
@billmeek I inadvertently removed the legacy attributes for older devices. Give this version a try.

**Comment by billmeek** [comment]
Excellent! Please apply to Video and Recording detail screens
and this will be done.

**Comment by billmeek** [comment]
@dmfrey all screens look good now, thanks.
