### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [MythTV-Clients/MythtvPlayerForAndroid#123]
Would you mind attaching the `.apk` files to the `releases/` here at Github, so folks without GPlay access can get them? No need for "historical versions", but if you could attach it for the latest and then for future versions it would be great. Thanks in advance!

**Comment by dmfrey** [comment]
I don't believe I can add the apk directly to the releases here as it just tags the repository with the version number. If you are aware of ways to do this, let me know and I will update our processes.

In the meantime, I have been putting the releases in dropbox. I will share the link to the repo and update the G+ community as well.

https://www.dropbox.com/sh/nhvpepzx6gcvlyc/AAAthel65MO4elPN5ijj7ztUa?dl=0

**Comment by IzzySoft** [comment]
It's pretty easy to do that. Steps are [outlined here](https://help.github.com/articles/creating-releases/). While tags are created on the `releases/` page automatically when you push them, you can convert a tag to a release (when creating a release, as described by the linked page, it lets you pick the corresponding tag) and simply attach additional files to it. Optionally, you can even include a description (e.g. a short log of the most important changes/new features).

If I can assist you further with this, don't hesitate to ask me :)

**Comment by dmfrey** [comment]
but it has to have a built APK. This occurs in a separate process. Am I
missing something? Git releases just tag the repo. If I created a release
in Github, doesn't it just create a zip of the repository?

**Comment by IzzySoft** [comment]
That's correct. Github just creates a `.zip` and a `.tar.gz` of the source, no `.apk`. But once the tag is there, you can create a release, assign it to the tag while creating it, and at the same time attach additional files – in our case, the `.apk` you've built. Again, the `.zip` and `.tar.gz` are created automatically by Github *when a tag is created* – a release is, so to speak, building on top of that. Github creates no additional files when you create a release.

**Comment by IzzySoft** [comment]
Ooops – there it is, thanks a lot!
