### ISSUE TITLE
Convert SearchResultsModule to DynamicUseCase

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#129]

**Comment by dmfrey** [comment]
@billmeek Can you play with this branch a bit?

I don't believe it is ever going to download the whole recorded programs list anymore after the last commits.  However, because of this change, I had to change a few other things.

1. When TitleInfos list is downloaded, it attempts to remove any entries no longer present from the search database
2. When each title is selected, it now only downloads just the details for this title, removes any existing entries from search db, then adds the new ones from this result.

This has some unfortunate consequences:
1. Recorded Programs in search will never truely be fully in sync
2. Recorded Programs are only added to search once a Title has been clicked
3. There may be the case where stale data remains in the search db, although, I have tried to minimize this as much as possible

I think we should be covered for large recording libraries after this, however, we may run into the case where the same will afflict the app for large video collections.

**Comment by billmeek** [comment]
@dmfrey sure, I'll test a bit later. I hadn't been suggesting sole use of TIL and
then GRPL because of the search feature. But I believe it's the correct way to
go.

If I read this correctly, on the very 1st use of the app, search will only be looking
at the titles, nothing else will be available.

**Comment by dmfrey** [comment]
@billmeek Not exactly, the titleInfoList is never put in search results,
but only once you drill down to a list of episodes for a title will they
start to appear in search. On Android TV, you will always get the whole
list, there is no title list option. It is probably a little beefier, so I
don't think it will be a problem.

**Comment by dmfrey** [comment]
@billmeek Take a look at this branch. I refactored the ApiConnection a bit so the OkHttpClient can be autowired in. This allows me to initialize it a new class called NetModule. It is in the presentation package. This allows us to hook into a new Interceptor that was mentioned in the link I sent for changing the user-agent. It also has that Stetho library and another tool called LeakCanary (https://github.com/square/leakcanary) which will show if we are leaking memory anywhere.  Also, it has all the search changes for both the app and android tv.

**Comment by billmeek** [comment]
Neat. Since I'm using prodDebug, the leaks should display.
Good news is nothing's displaying.

I tried searching and there may be an issue. Your earlier point:
```
2. Recorded Programs are only added to search once a Title has been clicked
```
seems to be the case. I found that some titles worked and other's didn't.
After I drilled down to a non-searchable title's episode screen, it started
working.

Thinking about the user that just reported an out of memory fault on the
Developers Console. He reports having 10,000 recordings. Should the
search feature be limited to titles only? (using only the GetTitleInfoList
results.)

**Comment by dmfrey** [comment]
with this method, he would have to click every title group to populate all
the search results.  I am not aware of any search api that we could offload
this to the backend. Ideally, we would allow you to search everything,
anytime, but, because of the loading issues people are experiencing, i
think this is an acceptable tradeoff.  Videos will always load everything,
unless we try to page that from the backend, but is far too complex for the
likes of this app.

With this implementation, I don't believe we will see the loading error,
unless you have a very large video library.  However, that might have also
been related to me trying to log the results. It would have been a 15 mb
string in this case.

**Comment by dmfrey** [comment]
@billmeek do you think that this is an acceptable tradeoff to support those with large libraries?

**Comment by billmeek** [comment]
@dmfrey, I agree. And to be specific, this would change the search
feature on the app to look at titles only for all recordings.

Do you think there should be a Video/GetTitleInfoList that returns
the title+intid+inetref added to the Services API?

**Comment by dmfrey** [comment]
Videos are different, in that there is only one set of data. There aren't
multiple joined in tables, nor are there, technically, groups of videos
like a tv series. Well, I guess that is not necessarily true as you can
have a video series in videos.  Maybe Videos does warrant this, but I would
add in the Category (MOVIE, TV, ADULT, etc) as well as count (which would
mostly be 0, unless its a tv series).

If we base search on the TitleInfos, however, we would be limiting the
amount of fields we could search on.

If you agree, this is a good step for now I will do the PR and merge to
develop, and we could take the services api discussion off list. I want to
send this version to @SingingDwarf to test for the large library issue.

**Comment by billmeek** [comment]
I agree.
