### ISSUE TITLE
10"/7" Tablet Preview Images Are Cropped

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#13]
![screenshot_2015-03-22-12-10-47](https://cloud.githubusercontent.com/assets/1831699/6770409/0ae83c5a-d08d-11e4-9a03-b9d8f75e3b66.jpg)

**Comment by dmfrey** [comment]
This gets generated from the backend. Maybe on a tablet I can make that
view larger, so it can  show more of the image.

**Comment by billmeek** [comment]
FYI, here's the image from the backend.
![2632_20140808033100 mpg -1 313x-1](https://cloud.githubusercontent.com/assets/1831699/6771582/02d55b1a-d0b0-11e4-981c-9b9948f9f685.png)
