### ISSUE TITLE
Unexpected episodes displayed in titles that have multiple inetrefs

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#131]
The following Dvr/GetTitleInfoList responses lines are for 2 different subtitles
and inetrefs with a single title. Tested on release/2.0.3, but it isn't unique
to that branch.

```
{''Count': '1', 'Inetref': 'ttvdb.py_188011', 'Title': 'Masterpiece Mystery!''},
{''Count': '4', 'Inetref': 'ttvdb.py_286058', 'Title': 'Masterpiece Mystery!''},
```

In Watch Recordings, the above correctly display with the same title and
2 separate icons. The counts are also correctly displayed.

Pressing either icon, however, displays all 5 episodes. There should be
only 1 episode for the 1st and 4 for the 2nd (of the above.)

**Comment by dmfrey** [comment]
The problem here is how the data gets loaded from TitleInfoList and RecordedProgramList. Currently, when a TitleInfo is clicked, it passes along the Title, not the Inetref. We couldn't use the Inetref because not every title has an Inetref. Consider something loaded from the Miro connector or, I believe, if you did a manual record schedule. I don't believe it will necessarily contain an Inetref.

**Comment by billmeek** [comment]
@dmfrey in this case, there are inetrefs for all episodes returned
by Dvr/GetTitleInfoList. Here's the Watch Recordings screen that
looks perfect, note the counts of 1 and 4:

![screenshot_2016-04-29-18-34-37](https://cloud.githubusercontent.com/assets/1831699/14933092/75ef5ef2-0e49-11e6-895f-ce4d01710bde.jpg)

and here's one of the screens underneath "Masterpiece Mysteries!",
that should have only 4 episodes (but a 5th one is there in error.) The
other "Masterpiece Mysteries!", with a different inetref has the same
5 episodes, but only 1 should be there.

![screenshot_2016-04-29-20-36-29](https://cloud.githubusercontent.com/assets/1831699/14933135/5a1811d2-0e4a-11e6-932f-e9fd441d4dea.jpg)

**Comment by dmfrey** [comment]
i guess maybe need to think about sending along the inetref, if it exists, and then filter the results based on not only the titleregex, but also the inetref.

I thought this was more of a data consistency issue on the backend, was it not?

**Comment by billmeek** [comment]
Re: I thought this was more of a data consistency issue on the backend, was it not?

Yes, and in this specific case, when either of the shows are recording, there will be
a third blank banner with the same title because there's no inetref at that time.

**Comment by billmeek** [comment]
Does #129's closing change this issue? During recording, it's still
likely that the inetref will be empty. And some titles will never have
inetrefs, if the user so chooses. What I'm suggesting is that the
inetref is like a subtitle of these types of programs.

For example (mm=Masterpiece Mystery)
```
mm with no inetref    displays a single tile (which could have multiple subtitles that can't been known)
mm with inetref 1234  displays a single tile with only inetrefs 1234 in it
mm with inetref 4567  displays a single tile with only inetrefs 4567 in it
```
inetrefs that are the same, but have the ttvdb.py_ prefix would be considered
different inetrefs and appear grouped in a different tile. Or, for extra credit
the prefix could be ignored when doing the comparison.

**Comment by dmfrey** [comment]
@billmeek can you check that this is still an issue in the latest `develop` branch

**Comment by dmfrey** [comment]
@billmeek can you check that this is still an issue in the latest develop branch

**Comment by billmeek** [comment]
@dmfrey ref #212 for now.

**Comment by billmeek** [comment]
It's still an issue (whether it should still be is another question.) On the
backend I've got this:
``` sql
+---------------------+-------------------------+-----------------+
| title               | subtitle                | inetref         |
+---------------------+-------------------------+-----------------+
| Masterpiece Classic | Churchill's Secret      |                 |
| Masterpiece Classic | Indian Summers Season 2 | ttvdb.py_290342 |
| Masterpiece Classic | Indian Summers Season 2 | ttvdb.py_290342 |
| Masterpiece Classic | Indian Summers Season 2 | ttvdb.py_290342 |
| Masterpiece Classic | Indian Summers Season 2 | ttvdb.py_290342 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
| Masterpiece Classic | Mr. Selfridge Season 4  | ttvdb.py_261633 |
+---------------------+-------------------------+-----------------+
14 rows in set (0.00 sec)

```
On the app Watch Episode page, there are three boxes and they
correctly display 1, 4 and 9 in the episode count in the lower right
corner. In this case, there isn't any artwork for Churchill's Secret
(so there's no clue what episodes might be below the box.)

But when any box is selected, the page below displays
all fourteen episodes as listed in the backend SQL above.

I'm thinking this feature should be reverted and display the
title as the backend does (without regard to the subtitle.)

**Comment by billmeek** [comment]
![screenshot_20170119-204053](https://cloud.githubusercontent.com/assets/1831699/22134014/9cd96c40-de89-11e6-8b1b-5692635e64cb.png)

**Comment by dmfrey** [comment]
@billmeek checkout branch `bugfix/issue_131` and test this out with your programs that have different inetrefs

**Comment by billmeek** [comment]
Perfect! I've only got one example of this (the Masterpiece Classic one
above.) There will be an edge case while a recording is being made
that hasn't had mythmetadatalookup run yet.

In the above, the counts match the number of programs for
each subtitle. There are no longer 14 recordings for each
subtitle.
