### ISSUE TITLE
Upper left arrow doesn't work (develop branch)

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#139]
Go to Watch episode -> select a title -> press the arrow
in the upper left corner. The normal 'click' sounds, but
the screen doesn't change. Pressing back returns works
just fine.

Mostly here so I don't forget to test it.

**Comment by dmfrey** [comment]
This is working on my phone. Try a clean, rebuild and redeploy?

**Comment by billmeek** [comment]
No joy, but 6.0.1 it works OK for me too. 4.0.4 is where it's
not working. This is in LogCat each time the <- is pressed:
```
org.mythtv.android E/NavUtils: getParentActivityIntent: bad parentActivityName 'org.mythtv.android.view.activity.TitleInfoListActivity' in manifest
```

**Comment by dmfrey** [comment]
@billmeek did this commit fix your issue?

**Comment by billmeek** [comment]
Yes, the <- arrow works on branch bugfix/issue_139.

**Comment by dmfrey** [comment]
awesome. I'm gonna merge this in
