### ISSUE TITLE
Update Watched Status doesn't work for episodes recorded after scheduled start time.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#144]
I believe that this:
```
presentation ... /presentation/presenter/ProgramDetailsPresenter.java line 129
    parameters.put( "START_TIME", this.programModel.get .getStartTime() );
```
is using the time the program is scheduled to start, rather than the time when the
recording actually started (and explains why it works most of the time.) This works:
```
this.programModel.getRecording().getStartTs()
```
@dmfrey, I know how to fix it, but do I create a new branch off of 2.0.3 or develop?
And should I create a 2.0.4 Milestone or just use 2.1.0?

**Comment by dmfrey** [comment]
@billmeek do we need to push a release for this bug? If not, just leave it in 2.1.0. Create a bugfix/issue_144 branch, commit your changes there, then build a pull request. When the tests pass merge it into develop.
