### ISSUE TITLE
Home->RECENT only displays recordings in the 'Default' Storage Group

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#149]
StorageGroup=Default is used when Dvr/GetRecordingList is sent
to populate the Home->RECENT screen.

Some users will report missing recordings if they have them in
other Storage Groups.

Tested on the current develop branch.

**Comment by dmfrey** [comment]
The problem is, if I don't limit it, I also get LiveTV, so you will get
less than 10, or, depending on live tv activity, none at all.

**Comment by dmfrey** [comment]
I actively remove LiveTV recordings

**Comment by dmfrey** [comment]
@billmeek what do you recommend we do in this situation?

**Comment by billmeek** [comment]
If you're filtering out LiveTV as you mentioned earlier, then how
about dropping the StorageGroup parameter. The existing BE
code looks for the parameter and if it's there, then it makes
sure only that Storage Group is used.
``` c++
(!sStorageGroup.isEmpty() && sStorageGroup != pInfo->GetStorageGroup())
```
