### ISSUE TITLE
Watch Videos: When the screen is entered, two Video/GetVideoList queries are sent

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#156]
The queries are .02 seconds apart per Wireshark. Note that inspector
doesn't always catch both. The duplicates also appear in LogCat.

Tested on the develop and feature/issue_129_dynamic_search
branches.

**Comment by billmeek** [comment]
For this test case, the returns were 304s as my Video collection
is very static.

**Comment by dmfrey** [comment]
@billmeek is there a difference in the querystring parameters being sent? This page utilizes a ViewPager, which will attempt to load the 2 adjacent pages, each of which needs to make a call. When you are on the first page, however, it will only load the current page and the one immediately to the right. Subsequent calls will pull from cache and the http response cache (HTTP 304).

**Comment by billmeek** [comment]
The queries are identical. This from the issue_129_dynamic_search_branch:
```
Request URL:http://192.168.1.200:6544/Video/GetVideoList?Descending=false
Request Method:GET
Status Code:304 Not Modified
Request Headers
Provisional headers are shown
Accept:application/json
Accept-Encoding:gzip
Connection:Keep-Alive
Host:192.168.1.200:6544
If-None-Match:"fd4c3b5fc409e19fe8eb9a22f3482b0818265fb7"
User-Agent:Mythtv Player/2.0.3
Query String Parametersview sourceview URL encoded
Descending:false
```

**Comment by dmfrey** [comment]
after looking at the logs, i can see that both the movie list tab and tv list tab are both loading at the same time, so cache has not been filled yet, so both are making the call. Plus, it always seems to be going to masterbackend and not to local cache. Will have to look into that. I am more concerned about these messages I am seeing:

java.io.IOException: unexpected end of stream on okhttp3.Address

These seem to be happening on almost every call. Might be just the emulator I am using. I will try it on my phone when I get a chance. When these happen, I then get a HTTP 200 or 304, depending on if it was in the http cache or not.

**Comment by dmfrey** [comment]
This is by design. I have set the default pages to keep in memory to 1, this includes the current page and 1 to either side. Since we start on the leftmost tab, it only attempts to load the one to right at the same time. Unfortunately, there isn't going to be anything we can do about this.  Also, since these are filtered by content type, once the data has loaded, it is required to load everything upfront and then it is up to the app filter them by type.

There is no way to tell the ViewPager to only load the current page and no others to the side. When you set the value to less than the default, it resets it back to the default min.

**Comment by billmeek** [comment]
Dan,

I believe I know why those happen. Looking at one right now. A previous
Dvr/GetTitleInfoList was sent and received a valid 304 response.

The backend then sends a TCP FIN response closing the conversation, but
the app doesn't respond with a FIN and apparently believes the conversation
to still be open. At the HTTP level, this makes sense because the Keep-Alive
header was present both in the query from the app and in the response from
the BE.

The app then sends a Video/GetVideoList query using the previous conversation
and the backend responds with a TCP RST, because it knew the conversation to
be closed and the expected response from the app was a TCP FIN.

The app starts a new conversation and sends the GetVideoList query again and
all is well. But the process repeats, that is, the BE sends a FIN and the app
doesn't send one in response.

I waited 12 minutes and pressed Back on the tablet. When I pressed Refresh on
the Home->RECENT screen a Dvr/GetRecordedList was sent by the app (as expected)
but it went to the connection in the previous paragraph that had been closed
by the backend and got a TCP RST (as it should.)

2 questions, why the backend is closing the conversation at the TCP level and
why isn't okhttp honoring the TCP FIN. I don't know either answer.

We've been down this road before. I even had a ticket open in Trac on it, but
the problem went away!

You can see this with the inspector too, the queries will be in red followed
by successful ones.

On 05/13/2016 03:13 PM, Daniel Frey wrote:
> java.io.IOException: unexpected end of stream on okhttp3.Address


-- 
Bill

**Comment by dmfrey** [comment]
Can I set a different value for keep-alive that would allow the
conversation to complete correctly? What is the backend expecting?

**Comment by billmeek** [comment]
Just tried 1 second rather than 10 and get the same failure. I'll
try some more, but I should really open an new issue.
