### ISSUE TITLE
Integrate Fastlane Supply

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#163]
Fastlane Supply is a command line tool for updating Android apps and their metadata on the Google Play Store

https://github.com/fastlane/fastlane/tree/master/supply

**Comment by dmfrey** [comment]
@billmeek Can you take some new screenshots of the current app on your 7 and 10-inch tablets. Please make sure to appropriate blur any content: images and names. Take a look at what I did in the tvScreenshots directory. I don't want to get flagged again :-)

I will take care of the phone ones.

I figure this could become a regular part of a release/ branch so that we can update any Google Play Store content at the time of release. Using this tool we can push all these changes at one time, including screenshots, changelogs, etc.

I will check with @dekarl to see if he can add/update the german versions of this as well.

**Comment by billmeek** [comment]
@dmfrey, looks like the plan is to move the images/store_listing/screenshots
directory contents. And probably delete store_listings completely?

I've got a new set of 10" images in my tree, I'll get the 7" later and push them.
Looks like we need some new standard images names, like Home.jpg

**Comment by dmfrey** [comment]
@billmeek, yes, those existing ones can go when this is all implemented.
Some standard names would be good as well. Pick some meaningful ones and I
will name accordingly.

**Comment by billmeek** [comment]
@dmfrey, I kept everything in .jpg from my tablet, did you use
gimp to convert to .png? I'll push a new README.screenshots
with short names, e.g. like nd.jpg for Navigation Drawer just 
'cause it's easy to rename them. let me know if that's OK.

**Comment by dmfrey** [comment]
No, I used Android Studio to do the snapshots. It's the camera button on
the Android Monitor tab. It creates pngs.

**Comment by billmeek** [comment]
@dmfrey, the monitor camera is much better, I've updated the README,
and picked the following names, but only kept the blured version because
I didn't want to risk the possibility of uploading a non blurred one. Assumes
that when using Gimp, the old file is overwritten.

Here's the new list:
```
    navigation_drawer.png
    about.png
    settings.png

    home_encoders.png
    home_recent.png
    home_upcoming.png

    watch_recordings.png
    watch_recordings_episodes.png
    watch_recordings_details.png

    watch_videos.png
    watch_videos_details.png
```
It's meant to be in the order that screenshots will be taken and lower case
just 'cause I'm lazy. I gave up on the shorthand name, e.g. ND for Navigation
Drawer.

**Comment by dmfrey** [comment]
@billmeek, this will work out great. I want to run through the Fastlane
Supply updating the images, data out there. I started a wiki page on
building a release. Take a look when you get a chance and fill in anything
I may be missing. The last section goes to the Fastlane Supply details. I
like that we can manage all of this right inside the codebase.

BTW, I used a Gaussian Blur set to 14.0 in GIMP. Just my preference. It
blurred the images enough to really distort them, however, you could still
kinda make out what it was underneath.

**Comment by billmeek** [comment]
@dmfrey take a look at the blur in the 7 and 10 inch watch_recordings.png.
I used 14 for everything, but those 2 look pretty visible. Here's the 10" one:

![watch_recordings](https://cloud.githubusercontent.com/assets/1831699/15410845/a3bfdefe-1de1-11e6-8c1e-e8f2de74ff9d.png)

**Comment by dmfrey** [comment]
i guess we will just have to see if they flag it and then make that blur
blurrier if they do.

**Comment by dmfrey** [comment]
@billmeek check out the google play listing with new screenshots. Fastlane Supply works good, so far. Looking forward to trying this out with the next beta release. Take a look at the wiki and let me know if you see anything I might be missing for building a release.  I had to remove some of the screenshots as the play store listing only allows for 8 screenshots per device size. Also, I moved your readme as that blew up fastlane supply when it was trying to deploy since it didn't know what that file was.

**Comment by billmeek** [comment]
@dmfrey I move the page under Development just to match like
pages. The move works, but I had to delete the page, as the
git mv didn't take. I have an extra copy of your work outside of
git on my host, just in case. I'll take read-through later.

**Comment by dmfrey** [comment]
that is perfect. That was my intention as well, just forgot to move it.
