### ISSUE TITLE
Consider using Firebase Analytics and Crash Reporting

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#165]
Google has announced the free availability of a suite of Firebase applications available to mobile applications across Android, iOS and Web. Two such products in this suite are Analytics and Crash Reporting. They are designed to complement one another. All triggered events are available on a console for easy cataloging and triaging.

https://firebase.google.com/docs/analytics/?utm_campaign=Firebase_featureoverview_awareness_analytics_en_05-18-16_&utm_source=GA&utm_medium=blog#key_functions

Would users be opposed to us tracking the usage and crash reports?

**Comment by dmfrey** [comment]
I created a Poll on the G+ Community. For the most part, people are ok with having this. One person wants the option to be able to disable it and 1 person so far has indicated they don't want this.

**Comment by dekarl** [comment]
https://medium.com/@gabri.mariotti/the-new-firebase-crash-reporting-fa411c6cf05b#.ekrowpjoi
It appears as if this depends on Google Play Services being available on the device, which may not be the case, e.g. for FireOS / Blackberry devices.

For FireOS there are crash reports available, too.
https://developer.amazon.com/public/community/post/TxDJW5O4CEBN9L/Crash-Reports-Now-Available

I'm not sure about the devices that use F-Droid though. At least crash reporting should be opt-in according to https://f-droid.org/wiki/page/FAQ_-_App_Developers#Can_I_track_users_from_my_app.3F

**Comment by dmfrey** [comment]
This will be disabled by default and opt-in from the user preferences. It
is my understanding that firebase sits outside of Google Play services. It
can be used across android, ios and the web.
