### ISSUE TITLE
Can't mark recording 'Watched'

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#225]
Mark Unwatched works from an episode's settings, however,
the recording can't be marked as watched.

**Comment by billmeek** [comment]
Note that the returned bool is always 'true' if the command is good,
no that status of the watched value
```
$ api --host mc0 --endpoint Dvr/UpdateRecordedWatchedStatus --wrmi --postdata RecordedId=7916 Watched=true
{'bool': 'true'}
$ api --host mc0 --endpoint Dvr/UpdateRecordedWatchedStatus --wrmi --postdata RecordedId=7916 Watched=false
{'bool': 'true'}
```

**Comment by dmfrey** [comment]
Hmm, i am finding the opposite to be the case. I can mark an episode watched, but can't mark it unwatched.

**Comment by dmfrey** [comment]
oh, i see what's going on. should be fixed shortly
