### ISSUE TITLE
Add check for master backend set in settings

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#240]
per @pot8oe 

Provide a check to make sure the settings have the master backend set

**Comment by dmfrey** [comment]
@billmeek @dekarl Testing can start on this.  It has now been moved to the Settings in both the app and Android TV client. It also unsubscribes from listening to network broadcasts when the screen no longer has focus.  I still need to address #241 and I believe this will most likely occur upon selection.  Before it proceeds, it will do a check of the backend version to validate it meets the minimum requirement.

**Comment by billmeek** [comment]
Dan,

Sorry, been mega busy. Works for me, but I don't have the other odd-ball
versions. Note that there will be no 0.29, rather 29.0 (or its current name,
29-pre.) Or, maybe I should say, if built correctly, there will be no 0.29.
We've seen folks choose their own naming schemes.
