### ISSUE TITLE
App Settings needs clean up

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#242]

**Comment by billmeek** [comment]
Not sure if your ready to test, but try UPCOMING.
I get: There was an application error  TROUBLESHOOT

**Comment by dmfrey** [comment]
@billmeek Give this branch a go. It is a precursor to #178. It aligns the settings across devices as well as cleans up unused ones.  Also, note that all the filters have been put back in place (recording groups for tv shows and parental levels and content ratings for videos).

I will put something in place in the settings to handle the backend discovery feature.

**Comment by billmeek** [comment]
@dmfrey, the recording group filters work fine, but they apply
at the episode list level. I'd have guessed that the filter would
have excluded the entire series (e.g. filter out all series at the
Watch Recordings page.) If possible, it makes it more obvious
that a filter is active.

**Comment by dmfrey** [comment]
@billmeek The `/Dvr/GetTitleInfoList` endpoint doesn't return the recording group. That data only exists at the episode level.  I can try to replace getting title info details with getting all the details and then filtering them client-side to determine this.  I know there was an issue with doing this a while back and was hesitant to do it again.

If you don't think this will be an issue, I can go ahead and replace this call with a call for everything and map it accordingly to a `Series` and add the recording group to and create a new filter to handle it.

Let me know your thoughts.

**Comment by billmeek** [comment]
Right, I think we've been down this road. If the change is made to get
everything, then I recall the problem with users that thousands of 
recordings. I'm OK if it's left as is. If users revolt, then revisit is as a
feature.

As to my (much) earlier comment about testing this fix and the UPCOMING
tab, I haven't been able to reproduce it. The last unusual thing I've done was
to Clear cache/Clear data.

**Comment by dmfrey** [comment]
yeah, i took care of the issue with the upcoming in a previous commit.

**Comment by dmfrey** [comment]
@billmeek the PR for this issue can probably be merged to develop as well.  Let me know if you think there are anymore issues with it

**Comment by billmeek** [comment]
@dmfrey, I'm done testing this one. Merge away.
