### ISSUE TITLE
Dvr/GetSavedBookmark not found on some users backends

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#243]
For some reason, users' backends do not have the endpoint `/Dvr/GetSavedBookmark`. Their backends need to be updated, but the app needs to handle this more gracefully.

**Comment by billmeek** [comment]
Should the app be looking at the version for various
services:
``` json
 api --host mc0 --endpoint Dvr/version --oneline
{'String': '6.3'}
api --host mc0 --endpoint Myth/version --oneline
{'String': '5.0'}
```
etc.

**Comment by dmfrey** [comment]
A user pointed me to this

http://lists.mythtv.org/pipermail/mythtv-commits/2016-May/111666.html

I haven't looked yet.  He is on mint and another is on arch and both had
the same issue.  I have a fix ready to go and had one of them test it for
me.  I will push it tomorrow.
