### ISSUE TITLE
Firebase: Exception java.lang.StringIndexOutOfBoundsException: length=7; regionStart=0; regionLength=-1

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#246]
App version:  3.0.3.

I suspect this is generated when a distribution uses their own
version string, rather than MythTV's (v29-pre-293-g41f4cc7.)
But I don't see the MythTV version in the Firebase report.

https://console.firebase.google.com/project/mythtv-player/monitoring/app/android:org.mythtv.android/cluster/c926a180

The failing line, may be due to a missing dash, is:
``` java
result = result.substring( 0, result.indexOf( "-" ) );
```
from: presentation/view/activity/phone/TroubleshootActivity.java

An  option could be using the Service versions (that distro's shouldn't
be messing with) like:
```
From: libs/libmythservicecontracts/services/*.h
Capture:   "1.4"
Channel:   "1.5"
Content:   "2.0"
Dvr:       "6.3"
Frontend:  "2.1"
Guide:     "2.2"
Image:     "2.0"
Myth:      "5.0"
Video:     "1.3"
```

**Comment by dmfrey** [comment]
@billmeek this has been updated in `feature/bugfix_246`.

Also, the links to firebase don't go anywhere. It takes you to page that says something like not in date range.  Just an FYI.

**Comment by billmeek** [comment]
I removed the '?duration=86400000' from the link. That works now.
I saw the same error about range with the duration when I tried it
today. The duration filter was set to 24 hours in mS.

**Comment by dmfrey** [comment]
ah, didn't even think to check that.  I will keep an eye out for it in the
future

**Comment by billmeek** [comment]
As to the test of the version. I didn't get any hits in G+ about
other distros versioning conventions. http://smolt.mythtv.org/static/stats/stats.html
has some data that may show why getting the version won't
be reliable. It's under the MythTV_Data tab on the far right.

Looks like the issue is where distros use a git SHA1 where the
expected version should be. Also, there's one "Unknown" in the
list.

 Here's a sample:
```
v0.28	2793	52.2 %	
v0.27	1088	20.3 %	
v0.27.6	660	12.3 %	
v0.27.4	137	2.6 %	
v28.0	135	2.5 %	
v0.27.5	130	2.4 %	
v0.25.2	77	1.4 %	
v29	59	1.1 %	
Unknown	48	0.9 %	
v0.27.3	43	0.8 %	
b6ae90c071	34	0.6 %	
v0.25.3	23	0.4 %	
v0.27.1	22	0.4 %	
3543e74534	18	0.3 %	
9d871a9	13	0.2 %	
v0.26.2	11	0.2 %	
...
```

**Comment by dmfrey** [comment]
hmm. feel free to add more tests to UtilsTest.java.  It looks like we need
to add a few more conditions to this before its completed.  It looks like
we can just fail things like `Unknown` or anything that fails to parse. I
will add a few more to them.

**Comment by billmeek** [comment]
I'm really leaning towards using the Service version, rather than
the MythTV version. E.g. BE:6544/Dvr/version etc. As long as a
single Service represents the MythTV version, wouldn't it suffice?

If not, then worst case it would require getting the version of all
Services used by this app.

Plus, the response is simpler: {'String': '6.3'}.

Also, I was thinking, if getting the version (either way) works, then
the Troubleshooting test for the Services API being up must be
working.

**Comment by dmfrey** [comment]
@billmeek I added checks for all other versions from that list.  We can always consider calling a different one to get the they major.minor version, though.

**Comment by billmeek** [comment]
The issue with
``` java
if( version.equals( "Unknown" ) || version.matches( "\b[0-9a-f]{5,40}\b" ) ) {
```
is that Unknown and SHA1s can be valid for 0.28+. The app can't tell.

Smolt says there are currently 28 odd-balls that are most likely SHA1s
plus the Unknown (which 48 users are on today.) Unknown
comes from the version.sh script in the MythTV source, in this line:
``` sh
SOURCE_VERSION=$(git describe --dirty || git describe || echo Unknown)
```
So some folks aren't using git at all. Or git describe is failing.

FYI, the info in Smolt is from users that opt-in, so it's a good sample,
but not absolute.

**Comment by dmfrey** [comment]
Which service is a better one to use?

**Comment by billmeek** [comment]
0.28 was formally released on 4/11/2016. 0.28.1 was just released and includes
the Get and Save Bookmark and that would be Dvr/version = 6.2.

6.2 could exclude some users that are still running on an old 0.28
version. But the should really be updating.

I added Myth/GetBackendInfo back on 1/19/2016.

6.3 added things like StopRecording that shouldn't be of interest to
this app.

For the future of this app, it's possible that Dvr/version won't be the
indicator of a minimum version. A flexible Service choice would be
good. I don't know why, but could see a test of multiple Services.

**Comment by dmfrey** [comment]
@billmeek are these service versions produced as a part of an endpoint call? It can get complicated pretty quickly to try to support all these various versions of endpoints.  However, that would make going back to support v0.27 a possibility. There would be a bunch of refactor work needed to support this.  Maybe we use what's here for now, if it satisfies all, and disregard the `Unknown` or `SHA-1` until we come up with another solution.

**Comment by billmeek** [comment]
@dmfrey, I believe they would be considered an endpoint, e.g.
``` 
$ curl -H 'Accept: application/json' mc0:6544/Dvr/version

{"String": "6.3"}
```
Just as a test, I changed the BackendVersionJsonMapper to only
look for a String and adjusted TroubleShootActivity to convert the 
String to a float and it worked (and changed Myth/GetBackendInfo
to Dvr/version.)

As to disregarding Unknown and SHA-1s, it maybe OK, given the low
percentages based on the Smolt samples. Maybe those users aren't the ones giving
the app low ratings ('cause they're using Mythbuntu that returns the
expected version string.)

**Comment by dmfrey** [comment]
@billmeek I think the bug for this Firebase Crash report is resolved. Let's start another issue to handle dealing with various versions of the api.

Let me know if you think the reported bug is not resolved.

**Comment by billmeek** [comment]
@dmfrey, Agreed, this issue is resolved. Opening a new issue for the version test.
