### ISSUE TITLE
Watch Recordings/Watch episode question screen title

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#248]
When selecting Watch Videos from the Navigation Drawer,
the next page is titled: Watch Videos.

If Watch Recordings is selected from the Navigation Drawer,
Watch episode is the title.

I know how to change it, but is Watch episode intentional?

string name="watch_recording"Watch episode

**Comment by dmfrey** [comment]
@billmeek Yes, this should probably be something like `Select Series` or `Pick a Series`. or something like that.  Change it as you see fit.

**Comment by dmfrey** [comment]
@billmeek what do you think it should say?

**Comment by billmeek** [comment]
@dmfrey,  ``Watch Recording`` (matches ``Watch video``.)
