### ISSUE TITLE
Compilation failure.

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythtvPlayerForAndroid#25]
I have installed the latest build tools 22.0.1 and I am getting the following compilation error:

:app:compileDebugJava
C:\Users\SBG\Android studioProjects\MythtvPlayerForAndroid\app\src\main\java\org\mythtv\android\player\app\recordings\TitleInfosFragment.java:141: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation( getActivity(), null );
                                                                                                               ^
  cast to Pair<View,String> for a varargs call
  cast to Pair<View,String>[] for a non-varargs call and to suppress this warning
C:\Users\SBG\Android studioProjects\MythtvPlayerForAndroid\app\src\main\java\org\mythtv\android\player\tv\TvItemAdapter.java:83: error: cannot find symbol
            category = (ImageView) parent.findViewById( org.mythtv.android.library.R.id.tv_item_category );
                                                                                       ^
  symbol:   variable tv_item_category
  location: class id
C:\Users\SBG\Android studioProjects\MythtvPlayerForAndroid\app\src\main\java\org\mythtv\android\player\tv\TvItemAdapter.java:84: error: cannot find symbol
            title = (TextView) parent.findViewById( org.mythtv.android.library.R.id.tv_item_title );
                                                                                   ^
  symbol:   variable tv_item_title
  location: class id

**Comment by billmeek** [comment]
Try removing: "org.mythtv.android.library.".

**Comment by tekrantz** [comment]
Ok, not sure I completely understand, but in Android Studio under the core project I deleted org.mythtv.android.library then did a git reset head (hard).  Then I built again and I get the same compilation error.

**Comment by billmeek** [comment]
@tafypz, I updated my original workaround above.

**Comment by dmfrey** [comment]
This was my fault. Something I was working on.  I will fix it immediately.
