### ISSUE TITLE
Firebase/Fatal: Exception java.lang.RuntimeException: Unable to start activity ... 'fabProgressCircle'

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#253]
3.0.6

Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mythtv.android/org.mythtv.android.presentation.view.activity.phone.TitleInfoListActivity}: java.lang.IllegalStateException: Required view 'fabProgressCircle' with ID 2131886552 for field 'fabProgressCircle' and method 'reload' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.

console.firebase.google.com/project/mythtv-player/monitoring/app/android:org.mythtv.android/cluster/7bfa6dc6

**Comment by dmfrey** [comment]
This is something I'm experimenting with. Its not deployed anywhere.
