### ISSUE TITLE
Firebase/Fatal:  Exception java.lang.RuntimeException: Unable to resume activity ... ProgressArcView.show()

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#254]
3.0.6

Exception java.lang.RuntimeException: Unable to resume activity {org.mythtv.android/org.mythtv.android.presentation.view.activity.phone.MainPhoneActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.jorgecastilloprz.progressarc.ProgressArcView.show()' on a null object reference

https://console.firebase.google.com/project/mythtv-player/monitoring/app/android:org.mythtv.android/cluster/0de71b7f

**Comment by dmfrey** [comment]
This is something I'm experimenting with. Its not deployed anywhere.

**Comment by billmeek** [comment]
Thanks for the reply.

Gets to the issue in my previous email about "Firebase 'development signature'"
And my experiment with the signature at the bottom of this page:

https://console.firebase.google.com/project/mythtv-player/monitoring/app/android:org.mythtv.android/cluster/3c869b32
