### ISSUE TITLE
Menu buttons stopped working after 3.0.6 update (on Android 5.1)

### ISSUE THREAD

**Issue by jaahaavi** [MythTV-Clients/MythtvPlayerForAndroid#267]
I have old Nexus 10 tablet which I have been using for watching mythtv.
Yesterday I updated to mythtv player app to 3.0.6 and after that update when I choose: menu -> Watch recordings i see list of all recordings as usual, but when I try to select recording it doesn't do anything.
I also tried this on my Honor 8 (Android 7.0) and in that it's working normally, so. when I press recording it switches to that page where I can select the episode and after selecting episode it goes to page where episode description is and I can launch external player.

Nexus 10 has Android 5.1 ("Lollipop").

**Comment by dmfrey** [comment]
@jaahaavi Thanks for letting me know. I will look into it.

**Comment by jaahaavi** [comment]
Tested all the old releases and the first one which was working with Nexus 10 was as old as 2.2.1. After that something happened and recordings from recordings menu can't be selected in 3.0.0. (I have been using mythtv with Nexus 10 almost every day for couple of years and always updating everything from play store. Quite odd that it took so long before that update arrived to mythtv)

Also I noticed when I compared it to my Honor 8 phone mythtv 3.0.6 that with Honor 8 I can select episode from home -> recent tab, but in Nexus 10 when pressing recording in recent tab nothing happens (only that android animation happens that it fills the selection box slowly when pressing the recording button). This happens also with that 2.2.1 version where recording menu is working.

Hope this helps on finding the bug.

**Comment by dmfrey** [comment]
Yes, that older version didn't have the recents tab clicking through to the
episodes. The later ones do as they are now really the same screens, but
just a different amount of data is shown.  Recents kind of mimics the
status page on mythweb.

Sorry for the delay, I have been out of town on business.

**Comment by dmfrey** [comment]
@jaahaavi I found the issue and am going to put out a branch to fix it.

**Comment by dmfrey** [comment]
@jaahaavi do you have the means to build and test the changes in [bugfix/issue_267](https://github.com/MythTV-Clients/MythtvPlayerForAndroid/tree/bugfix/issue_267)

If not, let me know and I can build it for you and make it available somewhere.

**Comment by jaahaavi** [comment]
@dmfrey I can test that fix if you build apk packet. (Sorry for this late answer, but my workload before my summer vacation was terrible)
