### ISSUE TITLE
Consistency: Display Title Over Episode In All Recordings

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#29]
@dmfrey, I remember you reversed this in the Search Results
screen. Suggest that it would make sense to make it the same
in the All Recordings screen.

**Comment by dmfrey** [comment]
@billmeek are you noticing this on episodes that do not contain a sub title?  Would just showing the title in place of an empty sub title in these cases suffice?  Or should it be something else?

**Comment by billmeek** [comment]
@dmfrey episodes, without a subtitle, display the title and date.
Perfect.

Episodes with a subtitle display subtitle, title, date.

Displaying title, subtitle, date would match the Search Results format
and be easier to read (in my  opinion.) Maybe this should be left open
 until 'real' users comment on it.
