### ISSUE TITLE
Titles With Special Characters Display In All Recordings, But Not In Watch Recordings Episode Lists

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#31]
The following 2 display in All Recordings, but not under Watch
Recordings. I removed the ó in the BE on the 1st line below
and refreshed the app and the recording appeared.

``` sql
sqlite> SELECT * FROM programs WHERE program_title LIKE 'Notic%';
RECORDED|1427927400000|1427929200000|NOTICIERO UNIVISIÓN|Noticiero Univisión|
RECORDED|1427925600000|1427927400000|NOTICIAS 66 UNIVISIÓN CHICAGO|Noticias 66 Univisión 
```
The query without the wild card works too:
``` sql
SELECT * FROM programs WHERE program_title = 'Noticiero Univisión';
```

**Comment by billmeek** [comment]
Cleared the app DB and they're displaying now.

**Comment by billmeek** [comment]
Let's see if I can get this right. To Duplicate:
    Force Stop, Clear Cache, Clear Data on the app
    mythbackend --setverbose http,upnp
    Restart and configure the app
    Go to a Watch Recordings line with a special character
    Select that entry [this is the step I left out when I closed it in error]
    Note that an all white page is displayed (except for the title in the top bar)
    Note that in the backend log, no messages have been received for the title under test

**Comment by dmfrey** [comment]
@billmeek which charset are these characters in? We are probably making requests in UTF-8. If they are in that same charset, i don't see why these wouldn't show.  I will have to try to find this particular show so I can record it and play with the data

**Comment by billmeek** [comment]
They are in UTF-8.  The ó in Univisión is 0xC3B3. I added 2
Spanish language stations to my lineup in Schedules Direct
to test it.

But, right now, the episodes ARE displayed in Watch Recordings.

@dmfrey, based on the BE log, when I refresh the WR screen,
the app sends a GET /Dvr/GetTitleInfoList. Could it be that I'm
not getting the new recordings until some else runs?

I'm thinking of closing this (again.)

**Comment by dmfrey** [comment]
That scheduled job for titleinfos should have been disabled. I will clean
that up. Since we are deriving this from the programs now, it is no longer
needed.

I scheduled that recording too to try it out as well.

**Comment by billmeek** [comment]
This whole issue has nothing to with special characters, rather my
assumption that when refreshing Watch Recordings, new data
would appear immediately.

I doesn't. I just re-added the ó to the title I had changed, refreshed
WR and the change wasn't there. Probably the 5 minute timer caused
a reload of all recordings and the change is there.

**Comment by dmfrey** [comment]
this might throw a wrench in here...on my nexus 6, this program loads fine in all calls.  On shows screen, on all recordings and clicking on this particular show to show just the episodes for that show.

When I do the same thing on my daughter's asus memo pad, i get no recordings when clicking on the show, but it does show on all recordings.

**Comment by dmfrey** [comment]
@billmeek can you retest this one and verify if it is still an issue. I have done some considerable work in this area and I believe new items show up instantaneously now once downloaded.

**Comment by billmeek** [comment]
Right now, my 4.0.4 11" isn't displaying the 2 Spanish Recordings, but I have the
same file copied over as a Video and it displays OK.

My L displays both the Recordings and Video OK. Both have fresh 1.1.10
loads and I did a Force Stop/Clear Cache/Clear Data before testing. I just
can't collect good data on this one.

**Comment by dmfrey** [comment]
I wonder if in 4.0.4 I need to specify for sqlite it is utf-8. Or, its
something with the java param I am passing in. Maybe I can force that
string to utf-8.

**Comment by billmeek** [comment]
Note that the recordings display in All Recordings and now in
Watch Video (on the same 4.0.4 tablet.)
