### ISSUE TITLE
Add Settings to set HLS Transcode Options

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#42]
requested by @fphillips

At this point going to make the settings with mythweb, unless otherwise requested

width: auto*, 288, 400, 480, 640, 800, 960, 1024, 1280*
height: auto*, 320, 480, 540, 600, 768, 720*
bitrate: 500k, 600k, 700k, 800k*, 900k, 1000k, 1500k, 2000k, 2500k, 3000k, 3500k
audio bitrate: 32k, 64k*, 96k, 128k, 192k

asterisk denotes defaults (auto is 0 and will let the backend decide)

**Comment by fphillips** [comment]
Hold up, it may not be necessary for me.
Do you remember this discussion: http://lists.mythtv.org/pipermail/mythtv-users/2015-January/375332.html
Did you get anywhere with that? I haven't tested much yet, but I noticed 0-byte files, except for the last file, which was hundreds of MB, as if all were being concatenated into it.

This may be why mine wouldn't play and the external player was getting the mpeg2 instead.

**Comment by dmfrey** [comment]
I was never able to resolve that. I ended up reinstalling mythbuntu. Needed
a new drive anyway. The external will always get the raw file. I am
handling the hls in the app.

However, it was a good suggestion and now people will have choice.

Actually, I could make it so that in the settings you could select either
external or hls. If you select hls, then you can set the hls settings. If
they are selected, the recording details will always show the queue hls
button and then the play button when the stream is ready. Or, if you don't
have hls enabled, you will only ever see the play button and it will launch
it externally.

Thoughts?

**Comment by dmfrey** [comment]
Also, what I found was that that issue did not exist on  v0.28. However, I
can't seem to get a successful hls transcode of most my movies, which is
partially why I haven't spent as much time on that section.
