### ISSUE TITLE
Honor Parental Controls

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#45]
Requested by user John Burroughs on the Mailing List

* Need to verify web services provide parental control data.
* Parental Control Management
  * Can parental controls be derived from the backend
  * Need to provide protected Settings for managing the parental level.
* Apply Parental Control level to Recordings
* Apply Parental Control level to Videos

**Comment by billmeek** [comment]
Video/GetVideoList returns: ```<ParentalLevel>4</ParentalLevel>``` (looked it up when I saw John's email :)
I don't see it in Dvr/Recorded (or in MythTV mythconverg.recorded.)

**Comment by dmfrey** [comment]
Are there any service calls that will return the current parental level set?

**Comment by billmeek** [comment]
Not directly, however this works.
```
<BE>:6544/Myth/GetSetting?HostName=<FE>&Key=VideoDefaultParentalLevel
```
It comes from FE settings: Setup -> Media Settings -> Video Settings -> General Settings
->  "Starting Parental Level" on the 3rd page.

The passwords could be retrieved the same way. Mine in the DB look like:
```
VideoAdminPassword = 4444 # seems to be the level 4 password
VideoAdminPasswordThree = 333
VideoAdminPasswordTwo = 22
```
Now, which FE should the app use for the settings. I guess the
same as the backend, however I'm not sure how that would
work for users that BE only systems (e.g. all remote FEs.)

**Comment by dmfrey** [comment]
Ah, so on the backend there is a password set per parental level?

Are the levels more restrictive low to high? 1 being the most permissive!

**Comment by gustden** [comment]
Since the parental control and passwords can be set differently on each frontend,  wouldn't you want to be able to set independent controls and passwords in the app?    As in my case,  I have the family room  set more restrictive than my bedroom.

**Comment by billmeek** [comment]
Yes, password per level, except 1 which must be no restrictions.
And it has no password. And 4 is the highest.

**Comment by billmeek** [comment]
Note that in 0.28-pre, GetSetting now returns a simple
    ```<String>settingORitsDefault</String>```
