### ISSUE TITLE
Use Numeric Portion Of inetref For Sorting Recordings

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#48]
Really from Eric Sharkey on the -users list.

Consider breaking up the inetref into inetref_prefix and inetref.
Sort only on the inetref. The delimiter is currently '_', but for a
time during development, it was a ':'. Users who archive their
recordings could have both separators as well as no prefix.

**Comment by dmfrey** [comment]
Do we use the inetref in any of our backend calls?  I will do some digging on this.

**Comment by dmfrey** [comment]
looks like using it to get the artwork. I think i will have to just have a separate column, like I have the title_sort column that just breaks out the number.  And just use it for grouping. This way I maintain the existing calls to the backend to get the correct artwork.

**Comment by dmfrey** [comment]
oops, looks like it is tvdb.py_, nothing at the end after the number

**Comment by billmeek** [comment]
Right, it's tvdb.py_ or, for a short time during the initial prefix addition,
tvdb.py:. The same is true for tmdb.py. So a user could have 4 inetrefs
for a single program: <nothing>, 12345, ttvdb.py:12345 and ttvdb.py_12345.
Actually, there are cases where there are tmdb prefixes where ttvdb should
be. But I think folks should fix that in the BE.

**Comment by dmfrey** [comment]
@billmeek can you clarify how you would want to use this for sorting?  Is this the case where you might see it with or without the prefix in separate entries?  Why would the backend put it in there one way for one recording and another or a different one?

**Comment by billmeek** [comment]
I was thinking of your email a few weeks ago that said 'sort on title only'.
That solves Eric Sharkey's issue and makes the app sort the way the
FE does. Personally, I like what you've done now. What would you 
think of another setting like "Sort Watched Recordings By Title or
Title and inetref"?

Then folks who have lots of old recordings with different versions of
inetrefs would choose Title only, while those who keep their metadata
in good shape could keep the Title/inetref way. Then you wouldn't need
to add a new inetrefNumberOnly column.

As to how it happens, some shows fail metadata lookup, and the recording
gets an empty inetref. Users can edit the recording rule and manually add
an inetref and future recordings will get that.  The : vs. _ is just that short
period  in development when the prefix scheme was being added.

**Comment by dmfrey** [comment]
I like the idea of a property in the settings.  Let's do that. Should be pretty straight forward to implement.

**Comment by dmfrey** [comment]
@billmeek so this is not as straight forward as I initially thought.  Also, the more I think about it, the more I don't want to do this.  If this gets implemented, then different shows with the same name will be grouped together.  For instance, I had originally setup to record the show Empire. Didn't actually watch it, but needed some recordings to play with.  But this rule on the backend also recorded another show called Empire, but this had to do with building the Empire State Building.  The backend couldn't distinguish between the 2 shows.  I actually have 3 entries in my Watch Recordings list, because the first one has the wrong inetref.  In that case, I could see joining them, but it would be more suited to fixing the metadata on the backend and not in the app.  An app like this really depends on the backend having the right data in the right places.

What do you think?

**Comment by billmeek** [comment]
@dmfrey, don't programs like your Empire examples get grouped together
in the MythTV frontend now? If so, then Eric's title only sort should
work (app would display the same as the FE.)

I agree about the quality of metadata. Right now, last Sunday's
showing of Mr. Selfridge has no inetref, and the app correctly
(my opinion) displays it separately from those that have an
inetref with the existing title/inetref sort.

If you'd prefer to use a title only search, I'm OK with it.

**Comment by dmfrey** [comment]
i will have to verify that with my frontend.  I think they are all grouped
together by title, but I will check tonight.  Going back to just title will
be a bit of a reversal. Let me think about it a bit.

**Comment by billmeek** [comment]
I'm even more OK if you keep the existing sort ;).

**Comment by billmeek** [comment]
The issue has a fairly long history beginning with a bug in MythTV's
GetTitleInfoList (doesn't return titles without an inetref in 0.28-pre.) 
In the app, original testing revealed that some titles were displayed,
but had no episodes underneath. That was resolved and also the
sorting was rewritten to handle the case of different inetrefs on the
same title. It did not address the multiple versions of inetrefs that
will appear especially for users with old recordings that existed
prior to the inetref prefix change(s).

The app was designed to honor good metadata and in this case,
fixing it would solve the issue. Also, there are at least three users
that have spoken up regarding the use of different inetrefs for the
same title. Significant work was done to the app to allow that to 
happen and after discussion off-issue the decision to keep the
existing sorting in place.
