### ISSUE TITLE
Support Recording Groups and Passwords

### ISSUE THREAD

**Issue by SiliconFiend** [MythTV-Clients/MythtvPlayerForAndroid#49]
Please consider supporting Recording Groups as a filter, with support for their PIN/password as set in Mythfrontend (On the Watch Recordings screen, with the cursor in the Groups, press the Menu button and select "Change Group Password"). It's possible the Recording Group password may not be available via the services API. Thanks!

**Comment by billmeek** [comment]
@dmfrey, FYI, the group names and passwords are stored in the
recgroups table. There was a single setting table entry, but that was
removed in 8/2010. The recgroups table isn't accessible from the
Services API.

**Comment by dmfrey** [comment]
For parental levels, these appear to be set per frontend.  Is this also the
case for Recording Groups?  If so, then it is probably better the app
maintain its own list of pins/passwords for these features.

**Comment by billmeek** [comment]
Recording Groups are not host specific:
``` sql
mysql> SELECT * FROM recgroups;
+------------+----------+-------------+----------+---------+
| recgroupid | recgroup | displayname | password | special |
+------------+----------+-------------+----------+---------+
|          1 | Default  |             |          |       1 |
|          2 | LiveTV   |             |          |       1 |
|          3 | Deleted  |             |          |       1 |
|          4 | TOH      | TOH         | toh      |       0 |
+------------+----------+-------------+----------+---------+
```

I'd agree that a 'per device' solution makes sense, especially for phones.
Tablets might be more likely be used by the whole family. So could the
current user be checked? What about the case where dad leaves himself
logged in and son picks up the tablet and watches something that wasn't
intended for young eyes.

MythTV seems to prompt once per session (for Parental Level, I don't
know about Recording Groups), maybe the app has to prompt once per
recording. And, of course allow no passwords for those that don't need
the feature.

**Comment by dmfrey** [comment]
@billmeek I am trying to come up with an appropriate design for this.  I am thinking of swiping from the right of the screen to open a second drawer that allows you to select the recording group.  Other option would possibly be to have a menu item that pops a dialog to allow you to select it.  However, I kinda like that it is out of the way with the right drawer.  I think the drawer gives us most flexibility for adding other options.  I am gonna dig a little deeper into standards for this.

**Comment by SiliconFiend** [comment]
It would also be nice to provide a way to choose the initial/default recording group (the standard MythTV frontends have this function).

**Comment by dmfrey** [comment]
@SiliconFiend that would be possible, but probably after initial load of the app data so I can see what is available

**Comment by dmfrey** [comment]
@SiliconFiend What other recording groups do you have besides Default, LiveTV, Deleted, other standard ones, etc.  The app never shows anything that is deleted or LiveTV.

**Comment by SiliconFiend** [comment]
Well, the one I would want to be able to choose as an alternate default is one I've set up for the kids' recordings. By the way, I checked and the passcode is global across all frontends.

**Comment by dmfrey** [comment]
@billmeek I started to implement this, got it mostly done actually.  However, TitleInfoList does not have the Recording Group in it. So might have to go back to using just the programs table and ditch the title info list altogether.  What do you think?

**Comment by billmeek** [comment]
@dmfrey, Makes sense to ditch it. Too bad, TitleInfoList would
be a good choice for the top level recording list where little detail
is required. It would be interesting to allow the client to tell TitleInfoList
what additional fields to return, e.g. a new parameter like:
Wants=recordgroup,inetref,season,episode
but I think that breaks the design intent on the BE (keep the client
insulated from the SQL.

**Comment by dmfrey** [comment]
@billmeek try this out with your different recording groups and let me know how it goes.  Enable it in Recording Settings and then select the different group to change it.

**Comment by dmfrey** [comment]
also, I think we should move security for these to a separate issue.  Get all the base functionality working first, then implement security app-wide.  What do you think?

**Comment by billmeek** [comment]
In All Recordings, my This Old House recording group (named TOH)
displays perfectly.

In Watch Recordings, all titles display and all are empty with the
exception of This Old House. It has the correct number of episodes.
It might be 'prettier' if the Watch Recordings screen could have only
the titles for the selected group too.

Search results display any existing episode even though I've set my
Default Recording Group to TOH.

We may need to define how this should be tested if the above are
design intent.

**Comment by dmfrey** [comment]
This was the intent...

1. Only display titles in selected recording group
2. Count should reflect episodes of recording group
3. Episodes in titles should reflect those in recording group

Looks like in need to play more with recording groups on the backend so I
can recreate this better in the app

**Comment by billmeek** [comment]
@dmfrey good info. I missed the Count part of All Recordings.
Even though only my TOH ones display, the count is 217 (which
is the same without the Recording Group filter turned on.) It
should have been 14.

**Comment by billmeek** [comment]
Significantly better. The only thing that may be of concern is in
Search Results. When my TOH Recording Group is selected,
only This Old House episodes display - Perfect.

However, when I select the Default Recording Group, and search
for This Old House, it is found and displays episodes in Search
Results. I would have guessed that it wouldn't.

**Comment by dmfrey** [comment]
Should search truly be global, or, should it also honor the recording
group? Is there any equivalent to this on a traditional front end?

**Comment by dmfrey** [comment]
If we are going to put a pin on the settings, should you only be allowed to
change the recording group in the settings?

If so, then we should probably make the search also honor the recording
group and parental controls for videos

**Comment by billmeek** [comment]
The search in MythTV is only available for scheduling
recordings. Not for viewing them. I'd say the answer to your
question is no, nothing in the traditional FE.

In the app, I ``think`` the search should be restricted per
the user's choices.

Seems like the goal here is "Kid Safe". I'm wondering if an
overall adult password is all that's required. Once setup, 
the Ratings selection and available Recording Groups
would be fixed. My 2¢.

@SiliconFiend, you started this ;), does the above make sense?

**Comment by SiliconFiend** [comment]
I'm not sure what the mechanics would look like. I'm pretty satisfied with the way it works in the Myth frontend, where it prompts for the group PIN whenever you try to change to the protected recording group. We don't currently use the restrictions in the videos since it's pretty much filled with the kids movies anyway, so I don't know what that would look like.
