### ISSUE TITLE
Watch Video/TV/Queue HLS/PLAY Fails: Handle Spaces (etc.) In File Names

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#52]
I think the URL needs to be urlencode, as the following file
isn't found in the backend (the filename only shows up as:
/StorageGroup/Streaming/Smila's) 

From Wireshark:

    GET /StorageGroup/Streaming/Smila's Sense of Snow.mpg.640x480_800kV_64kA.m3u8 HTTP/1.1\r\n

From mythbackend.log

```
ExtractMethodFromURL(end) : Smila's : /StorageGroup/Streaming
HttpServer81 httprequest.cpp:938 (FormatFileResponse) - HTTPRequest::FormatFileResponse('') - cannot find file
HttpServer81 httprequest.cpp:365 (SendResponse) - HTTPRequest::SendResponse(xml/html) () :404 Not Found -> 192.168.1.235
```

**Comment by dmfrey** [comment]
@billmeek This is a big one.  I am pushing a special release just for this.  I have found that bumping up the bitrate on my HLS trancodes to at least 15000 and urlencoding the path solves the video playback issue.
