### ISSUE TITLE
Recordings No Longer Display "Ready To Stream" on 1.1.10.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#55]
When selected, the recording screen displays QUEUE HLS.

**Comment by dmfrey** [comment]
Was this after a wipe or clear data. It just needs to resync all the
programs and live streams the first time. I should probably sync the
recordings and videos first now, then the live streams so they can map up.

**Comment by billmeek** [comment]
It was after a Force Stop, Clear Cache, Clear Data. No change
after 22 minutes.

Works OK on 4.0.4, but not L.
