### ISSUE TITLE
Recordings: Missing All Titles Without inetrefs

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#62]
Running on: mythtvplayer-1.1.10-12-ge6cffca

I reverted 1690107 (#58)  and that didn't make them come back.

**Comment by dmfrey** [comment]
I think for this we will need to get the backend updated to return all
titles, whether a inetref is present or not.

Did we have an earlier issue for the same issue?

**Comment by billmeek** [comment]
We did, and it was the reason for switching away from GetTitleInfoList.

Dvr/GetTitleList returns everything, however it has nothing other than
the title.

I'll take this for now and put my 2 line fix back. I didn't write a ticket in
Trac at the time because the app wasn't going to use the endpoint.

**Comment by dmfrey** [comment]
Refresh me on what the 2 line fix was?  You mean on the backend, correct?
That let's all the titles come down.  No i think i am remembering it.

**Comment by billmeek** [comment]
Yes, the 2 line fix is in the backend. I edited my initial reply and
added the BE diff there just in case anyone else wants to
apply it. I just searched the MythTV code and nobody is using
the endpoint (I'd be concerned if stewartm had it in the new
WebFrontend webserver.)

**Comment by billmeek** [comment]
MythTV ticket created: https://code.mythtv.org/trac/ticket/12446

**Comment by dmfrey** [comment]
reverted app to use programs instead of titleinfos
