### ISSUE TITLE
Search Suggestions Colors make text unreadable on Android 4.x

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#65]

**Comment by billmeek** [comment]
Running on 1.1.12 at eec43e1. In 4.0.4 and 4.4.2, the text is
now very close to the background color. Works A-OK in L.

**Comment by dmfrey** [comment]
I believe this was fixed with a prior commit.  I have verified it on an 4.x phone.  @billmeek give a look as well and close if no longer an issue.

**Comment by billmeek** [comment]
Seems the same to me. The magnifying glass is invisible but
it's in the upper right. The show title is visible, but hard to read.

![screenshot_2015-08-09-11-41-11](https://cloud.githubusercontent.com/assets/1831699/9155825/2fcc1804-3e8b-11e5-9cc7-3b333088e577.jpg)

**Comment by dmfrey** [comment]
Oh, I thought this was referring to the search suggestions drop down when
you have search results in your history, not the search icon in the toolbar.
