### ISSUE TITLE
Nexus Player - Entering data with on screen keyboard and remote.

### ISSUE THREAD

**Issue by spearson2010** [MythTV-Clients/MythtvPlayerForAndroid#70]
On my Nexus Player I am unable to save data entered via the on screen keyboard.  For example, I enter the backend ip address using the remote and on screen keyboard, I click "Next", which moves the focus to the Cancel button.  The only option available on the on screen keyboard now is Done, which seems to press the Cancel button.  There doesn't seem to be a way to move the focus off the Cancel button.

**Comment by dmfrey** [comment]
@spearson2010 Here is an update on this.  I was able to reproduce this issue.  I found a workaround for you in the meantime...

1. Go to the preferences and select the Master Backend Address
2. Use the remote to enter the correct IP Address - DO NOT PRESS THE NEXT BUTTON on the onscreen keyboard
3. Hit the Back button on the remote when the ip address is fully entered. This will send focus back to the dialog box that popped up.
4. Click the OK button.

You should now be able to see your content on the other screens.  I know this is not ideal and I am looking into how to better handle the preferences in Android TV.

Please let me know if you have any questions.

**Comment by dmfrey** [comment]
closes #70

This is fixed in version 2.0.0. It now uses the new GuidedStepFragment implementation which provides for better navigation and text entry for the settings.
