### ISSUE TITLE
Provide large scroll button in All Recordings list

### ISSUE THREAD

**Issue by SingingDwarf** [MythTV-Clients/MythtvPlayerForAndroid#77]
With a large number of recordings, scrolling towards the bottom of the list can be tedious.

Modify scroll control on All Recordings list to provide a large scroll button, which allows user to quickly scroll around.

**Comment by dmfrey** [comment]
To be more performant, these episodes are lazy loaded, so the list is not
fixed until you reach the bottom.  Does the search feature help with this?
You can search on any field in the db just by typing it into the box.

**Comment by SingingDwarf** [comment]
The search feature does help massively, but I do find those applications with a 'fast' scroll much easier to navigate around. It would be quicker to scroll to a particular show, than have to type its name into the search box.

**Comment by dmfrey** [comment]
Found a library to provide fast scrolling, however, it can only be on the list views, not grid views, such as the video screens.  This is start, though.
