### ISSUE TITLE
Banners with white backgrounds prevent Back and Search icons from showing

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#82]
If the user touches the right area,the icons work just fine.
If the user swipes up, the icons display OK on the teal?
background. Titles that don't have any banner work OK
too.

Note that the title in the lower left of the following screenshot
is hard to read in the near white area.

Observed on 4.0.4, 4.4.2 and 5.1.1 running on mythtvplayer-1.1.11-24-g6807481

![screenshot_2015-06-11-21-23-30](https://cloud.githubusercontent.com/assets/1831699/8122522/a5627e66-1080-11e5-87eb-7b62d8958766.png)

**Comment by dmfrey** [comment]
I am not sure how easy it is going to be to animate the color of that.  I have noticed this in the google play tv and movies app as well, white text on white/light background.

**Comment by dmfrey** [comment]
@billmeek what do you think of the last comment?

**Comment by billmeek** [comment]
Re: the 'not sure how easy it is going to be to animate the color' comment,
I really don't understand the "animate" part. I see commented out AnimationUtils.animate
in the latest commit. Found some mention in stackoverflow.com and assume it's the
ability to change colors, not anything to do with moving pictures.

The description should have also mentioned that the voice search icon is
hidden too. Like the others, it works if the correct area on the screen is
pressed.

**Comment by dmfrey** [comment]
this is a tough one.  The things I am seeing are all hacks. One thing I can set is expanded text view and the collapsed text view. I think the problem is we are going to run into this one way or another. Either the image will be too light and the text unreadable. Likewise, if try to invert it, a the image would be too dark with dark text.  And that is just for setting the text.  It was even more of a hack to set the menu items and navigation. I will keep looking.

**Comment by billmeek** [comment]
Running on: mythtvplayer-1.1.13-1-dirty, commit: 0dfe6b7

Appears like the opposite of the 'all white' issue, with this
'very black' one.

This is unusual. The very 1st time the app is started, the
search and back icons are black on black. Displaying the
same screen again has the icons in white.  Even exiting
the program and restarting it continues to display OK.
If I Force Stop and Clear Cache, then the icons are black
on black until the screen is viewed again, and then they're
back to OK (white on black like the following screenshot.)

The title's text is always black on black. Works the same on
4.0.4 and 5.1.1.

![screenshot_2015-08-10-22-34-24](https://cloud.githubusercontent.com/assets/1831699/9189608/5e951c32-3fb0-11e5-85c1-847c7f01e857.png)

**Comment by dmfrey** [comment]
what happens if you scroll it and the banner collapses? based on this pick, i would expect the title to be black.

**Comment by billmeek** [comment]
You're right. If I scroll up, a black title "Scandal" can be seen on top
of the red graphic "CANDAL" in landscape, or "NDAL" in portrait.
