### ISSUE TITLE
An episode with no coverart displays white text on a near white background

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#84]
The program information is barely visible. Pressing in the
Play/Queue HLS area does work correctly

This occurs in Watch Recordings. Watch Videos is OK.

![screenshot_2015-06-13-17-52-09](https://cloud.githubusercontent.com/assets/1831699/8146280/30b7c8ca-11f5-11e5-868b-5db5fbdd92fa.jpg)

**Comment by dmfrey** [comment]
I am gonna turn off the color picking for a while.  I need to see if I can figure out if I can determine how light the color of the image is and swap it out for the default color.

**Comment by billmeek** [comment]
I didn't test the Play case, only Queue HLS (which works OK.)

The Play button is white on a white background. To duplicate:
In Watch Recordings, select any recording. Press Menu->Settings
and change the Internal Player off.

**Comment by dmfrey** [comment]
Hmm, which device, android os?  Mine are black text on white background.

**Comment by billmeek** [comment]
Samsung 7" and 10", nexus 7". 4.4.2, 4.0.4 and 5.1 respectively.
Also, the Play button is white on white for all recordings, not just
those without coverart. All running: mythtvplayer-1.1.11, commit: 5b71b83

**Comment by billmeek** [comment]
Portrait is OK, landscape is where it's unreadable.

**Comment by dmfrey** [comment]
Ah, OK, should be an easy fix if it is isolated to just that one view.
