### ISSUE TITLE
Selecting multiple tabs in Watch Videos requires multiple Back button presses to exit

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#85]
To duplicate (4.0.4 and 4.4.2, not L): Select Watch Recordings,
select each of the available tabs. One Back press will be required
for each tab pressed to exit the app.

Note that the tabs should be pressed left to right. If the MOVIES tab
is pressed last, the  multiple Back presses aren't required.

**Comment by dmfrey** [comment]
Is this watch recordings or watch videos? There are no tabs in watch
recordings. If it is watch videos, I coded it that way. Seems to be a
standard navigation flow, but let's discuss it. It is easy to remove if it
doesn't work out right with the app flow.

**Comment by billmeek** [comment]
Fixed title. I never noticed this before and assumed it was a regression.
If available, then I'd suggest making it possible to leave Watch Videos
with a single Back press.

Also noted that it operates the same in L as 4.x.x.

I *thought* that earlier in the app's life it was possible to exit the entire app
from Watch Videos too. Now the user is returned to Watch Recordings
and then one more Back exits the app.

**Comment by dmfrey** [comment]
With the move to the standard Navigation Drawer View now, it was removed to
back out of the app from Watch Videos.  I have not found a place in the new
model to re-enable that.

If you think back button should exit Watch Videos, I can remove that code
that forces that behavior.

**Comment by billmeek** [comment]
I'll close the issue and if more users are concerned, it can be
reopened. The workaround is to use use MOVIES, Back, Back
to exit from Watch Recordings. Maybe it's more of an education
thing.
