### ISSUE TITLE
No play button, only Queue HLS

### ISSUE THREAD

**Issue by to6** [MythTV-Clients/MythtvPlayerForAndroid#89]
In Version 1.1.11 I have no "Play" link as I've seen in the screenshots of PlayStore. There is only the link "Queue HLS" below the description of the recording. How can I enable direct playing?

**Comment by billmeek** [comment]
Hi,

Select Settings, DEFAULT PLAYER, Internal Player. You can do this
from the Navigation Drawer or from a recording.

**Comment by to6** [comment]
Thanks a lot. It's not exactly this I think. But your hint encouraged me to play around with the player options. I get the "Play" button only, if I disable both, internal and external player. Perhaps it's a translation problem, I'm using the german version.

**Comment by billmeek** [comment]
Glad you've got it working. 1.1.11 was the 1st version to have a
translation in it. And it was initially done via Google Translate. 
Another German user submitted changes that are included in
later releases.
