### ISSUE TITLE
Unable to playback on Sony Bravia KDL43W805CBU

### ISSUE THREAD

**Issue by SingingDwarf** [MythTV-Clients/MythtvPlayerForAndroid#90]
I have succesfully installed MythTV Player on my Sony Bravia KDL43W805CBU and can view the list of videos and recordings available on my backend. The fanart also displays correctly.

However, when I attempt to playback any recording or video, the system just displays the fanart. The left hand menu disappears and the system remains responsive (i.e. I can select Back), but the video does not play.

I have tried installing (seperately) both VLC and MX players, with the Internal Player option set to off.
I have also tried the Internal Player option set to on, also to no avail.

**Comment by billmeek** [comment]
Hi, please mention the version of your MythTV backend and the type
of recordings, HD or SD (we can talk about videos later.)

**Comment by SingingDwarf** [comment]
Apologies, I should have stated that I'm running 0.27.4+fixes.20150601

**Comment by billmeek** [comment]
That helps. Let me know if you're trying High Definition or Standard
Definition recordings. With mythtranscode, Queue HLS in the app,
HD will fail. Both Dan and I are running 0.28-pre. Why VLC is failing,
I don't know.

**Comment by SingingDwarf** [comment]
Sorry, these are all SD recordings.

Are any log files generated by MythtvPlayer for Android? Is there anyway to view them on the TV, or get hold of them somehow?

**Comment by dmfrey** [comment]
Take a look at these instructions to setup adb to remotely access the logs.
https://developers.google.com/cast/docs/android_tv#adb-tcpip

Unfortunately, if it is a vlc issue I won't be able to produce logs for
that.  But it sounds like it happens both internal and external.

Can you verify you have the url and port setup correctly in the interface.

@billmeek has instructions in the wiki on how to bump up logging on your
backend as well.

**Comment by dmfrey** [comment]
@SingingDwarf Can you install VLC for Android on your TV. Version 2.0.0 for Android TV plays content best with VLC for Android. You don't need to do any transcoding to HLS.  I will be pushing version 2.0.0 to the Google Play Store beta channel for the app shortly.

**Comment by SingingDwarf** [comment]
@dmfrey I would love to try this, but unfortunately I returned the Sony Bravia - just too many issues with the firmware, lack of advertised features and unresponsiveness.

**Comment by dmfrey** [comment]
Closes #90

Thanks for the info. Gonna close this for now.
