### ISSUE TITLE
doesn't always display all videos

### ISSUE THREAD

**Issue by brianjmurrell** [MythTV-Clients/MythtvPlayerForAndroid#91]
Per the [G+ thread](https://plus.google.com/115193849724776970568/posts/a7JGfojA3F6) I started yesterday, I am having problems where not all of the Movies and TV shows I have on my BE are being displayed in the Watch Videos page.

Most recently, I cleared all data in the app, re-entered by backend address and set my preferences and now it is displaying them again.  But I have had this intermittent not-displaying/displaying in the past so I am not entirely convinced that the problem is fixed for good here by just clearing data.

Time will tell I suppose.

**Comment by dmfrey** [comment]
@brianjmurrell can you attach the files here so I can check them for parsing issues?

**Comment by brianjmurrell** [comment]
But if the problem was parsing, why would they parse fully sometimes and not others?

I think what I am saying is that it feels like parsing is not the problem.

**Comment by dmfrey** [comment]
@brianjmurrell Please check again with version 2.0.0. Parsing and caching has been completely rewritten. Could you attach the JSON output of your video library so that I may implement a unit test in the app based on the new parsing?

**Comment by brianjmurrell** [comment]
On Sun, 2016-03-20 at 06:19 -0700, Daniel Frey wrote:
> @brianjmurrell Please check again with version 2.0.0.

Is that in the Play Store yet?  My device is not seeing a Myth Player
update (yet).  Maybe it will just take a while to notice.

**Comment by dmfrey** [comment]
Not yet. I am working on getting it out there.

**Comment by brianjmurrell** [comment]
OK.  Fair enough.  I will sit tight.

Cheers.

**Comment by dmfrey** [comment]
In the meantime, can you export the json of your video library?  I will
setup a test case to attempt to parse it.

    curl -X GET -H 'Accept: application/json' "
http://your_backend_ip:6544/Video/GetVideoList" -o videos.json

Attach it here and I will setup a test case for it.  Also include any
stats, such as number of videos, etc.

**Comment by dmfrey** [comment]
Please test again once you see version 2.0.2 push down to your device.

**Comment by dmfrey** [comment]
@brianjmurrell Are all your videos now showing with version 2.0.2?

**Comment by netwolfuk** [comment]
I am seeing the same for recordings (a much larger list is available in MythTV Android Frontend than in MythTV Player). How do I clear the cache?
I am running a build of b445b51 against Myth 0.27
I can email you a download. What curl command will get me the json file?

**Comment by dmfrey** [comment]
duplicate #113

**Comment by brianjmurrell** [comment]
I'm sceptical that this is a duplicate of #113.  I will of course defer to your expertise here.
