### ISSUE TITLE
REST with TitleRegEx and special characters misses episodes

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#96]
I have a title with ()s in it. On the Watch Recordings/
Watch episode screen, it displays OK.

But when I go to view a recording, there are none. Even
though the previous screen said there was 1.

The issue is that TitleRegEx truly handles regular
expressions, and the ()s are two of the special
characters.

Here's the actual url being used:
```
url=http://192.168.1.204:6544/Dvr/GetRecordedList?Descending=true&TitleRegEx=Weekend+ABC7+Eyewitness+News+%28End+of+Oscars%29
```
The %28 and %29 correctly get converted to ( and ), but since
that's part of a regular expression, the episodes don't display.

If I go to my browser and use the url above, it too returns no
episodes. If I prepend a backslash in front of the ( and ), then
the episodes are returned.

This is the list of special characters: $, (,), *, +, ., ?, [, ,], ^, {, | and }
as known to QtRegExp.

Ref: http://doc.qt.io/qt-5/qregexp.html

**Comment by dmfrey** [comment]
@billmeek I don't have any titles like this to test with. Please verify and let me know if it fixes it.  Take a look at the commit to see where I modified it. If you need to adjust it, go for it.

**Comment by billmeek** [comment]
@dmfrey, that doesn't work, but adding 4 backslashed works for this
specific case. I changed the title to this:
```
Weekend ABC7 Eyewitness News (End of Oscars) * $ ^ + . {x} [y] |
```
and is doesn't work. Trying to get all of the regex special characters
in one shot, but left out the ?. Since the regex isn't really being used,
would it make sense to revert to chanid/starttime?

**Comment by dmfrey** [comment]
We definitely don't want to encode ?, & and =, as they are a part of the querystring spec.

What do you mean revert to chanid/starttime? Don't use the TitleRegEx query?

**Comment by billmeek** [comment]
I see, at this point, the specific episodes aren't known, just the
titles, so TitleRegEx is the only choice.

But how does a title that contains characters from the regex set
get matched?

Since the encoding of  ()'s works, it appears that they're decoded before
the regex is used. That's why putting a \ in front of them worked for the
original case here. I thought that would apply to all of the regex characters
that were part of the actual title (that should be matched without any expression.)

I found that this works:
```
http://mc0:6544/Dvr/GetRecordedList?TitleRegex=Weekend%20ABC7%20Eyewitness%20News%20.End%20of%20Oscars.%20.%20.%20.%20.%20.%20.x.%20.y.%20.
```

That is, all of the regex characters in the title were replaced with periods. The
%20 above were actually spaces when testing from my browser (plus signs
work too, as expected.)

**Comment by dmfrey** [comment]
Maybe we then just drop all the special chars you mentioned and replace
them with %20 or +

**Comment by billmeek** [comment]
The 'specials' need to be replaced with dots.
Spaces  for the 'specials' wouldn't match.

There would be a chance for false positives, e.g.
"Some Title?" vs. "Some Title$". But at least the
episodes wouldn't be lost.

Maybe "Some Title [stuff]" vs. "Some Title {stuff}"
would be a better example. But I think both examples
are unlikely in the wild.

**Comment by dmfrey** [comment]
ok, so I will take that list from the original post for this issue and
translate them all to '.'

**Comment by billmeek** [comment]
Sounds good.

**Comment by billmeek** [comment]
This works if you don't already have it:
```

                String specialTitle = titleRegEx.replaceAll( "[\\$\\(\\)\\*\\+\\?\\[\\]\\^\\{\\|\\}]", "." );
                sb.append( "&" );
                sb.append( String.format( TITLE_REG_EX_QS, URLEncoder.encode( specialTitle, "UTF-8" ) ) );
```

**Comment by billmeek** [comment]
The commit works, but consider this: I put a ó before the y
in an existing title and see this in the LogCat:
```
TitleRegEx=Elementar.y
```
Is substituting a dot for all non alphanumerics too severe
(as opposed to only replacing the regex set?) I'm concerned
that some wrong foreign title will match most likely in the case
of different vowels.

I did get all my distinct titles and removed those that weren't
all alphanumeric. Of the 1219 left, I couldn't find any cases
where the existing logic would fail. But I don't have a very
rich set of foreign words.

**Comment by dmfrey** [comment]
OK, I would say let's wait until it gets reported as an issue.  We may need
to tweak that regex I put in there. However, if your change already
supports that, then feel free to add that back in there and use that
instead.
